const express = require("express");
const cors = require("cors");
const requestLogger = require("./utilities/requestLogger");
const routing = require("./routes/routing");
const errorLogger = require("./utilities/errorLogger");
const helmet = require("helmet");
const app = express();
const sheet = require("./utilities/problemofday");
const axios = require("axios");
const cheerio = require("cheerio");
const addData = require("./utilities/addData");

app.use(cors());
app.use(helmet());
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(requestLogger);
app.use("/", routing);
app.use(errorLogger);

app.listen(process.env.PORT, (err) => {
  if (!err)
    console.log(`Problem Server is started at port ${process.env.PORT}`);
  else console.log("Error in problem server setup");
});

module.exports = app;
// const agent = [
//   "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.0 Safari/532.5",
//   "Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9",
//   "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.514.0 Safari/534.7",
//   "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/534.14 (KHTML, like Gecko) Chrome/9.0.601.0 Safari/534.14",
//   "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.14 (KHTML, like Gecko) Chrome/10.0.601.0 Safari/534.14",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.27 (KHTML, like Gecko) Chrome/12.0.712.0 Safari/534.27",
//   "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.120 Safari/535.2",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.36 Safari/535.7",
//   "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/18.6.872.0 Safari/535.2",
//   "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.1 Safari/536.3",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.6 (KHTML, like Gecko) Chrome/20.0.1092.0 Safari/536.6",
//   "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.6 (KHTML, like Gecko) Chrome/20.0.1090.0 Safari/536.6",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/22.0.1207.1 Safari/537.1",
//   "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; en) Opera 8.0",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/28.0.1469.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/28.0.1469.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2869.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 AOL/11.0 AOLBUILD/11.0.1305 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3191.0 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.1; rv:21.0) Gecko/20130401 Firefox/21.0",
//   "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0",
//   "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/29.0",
//   "Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0",
//   "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:35.0) Gecko/20100101 Firefox/35.0",
//   "Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0",
//   "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0",
//   "Mozilla/5.0 (Windows NT 6.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0",
//   "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0",
//   "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.12 Safari/537.36 OPR/14.0.1116.4",
//   "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.29 Safari/537.36 OPR/15.0.1147.24 (Edition Next)",
//   "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36 OPR/18.0.1284.49",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36 OPR/19.0.1326.56",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36 OPR/20.0.1387.91",
//   "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36 OPR/28.0.1750.40",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.46",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36 OPR/47.0.2631.55",
//   "Mozilla/5.0 (Windows NT 10.0; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.4.0",
//   "Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/533.17.8 (KHTML, like Gecko) Version/5.0.1 Safari/533.17.8",
//   "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.2 Safari/533.18.5",
//   "Mozilla/5.0 (Windows; U; Windows NT 6.2; es-US ) AppleWebKit/540.0 (KHTML like Gecko) Version/6.0 Safari/8900.00",
//   "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.71 (KHTML like Gecko) WebVideo/1.0.1.10 Version/7.0 Safari/537.71",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20120422 Firefox/12.0 SeaMonkey/2.9",
//   "Mozilla/5.0 (Windows NT 6.0; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 UBrowser/5.6.13705.206 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Vivaldi/1.0.94.2 Safari/537.36",
//   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.90 Safari/537.36 Vivaldi/1.4.589.11",
//   "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.91 Safari/537.36 Vivaldi/1.92.917.39",
//   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 YaBrowser/17.3.0.1785 Yowser/2.5 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 Camino/2.2.1",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6pre) Gecko/20100907 Firefox/4.0b6pre Camino/2.2a1pre",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8; en-US) AppleWebKit/532.8 (KHTML, like Gecko) Chrome/4.0.302.2 Safari/532.8",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.464.0 Safari/534.3",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_5; en-US) AppleWebKit/534.13 (KHTML, like Gecko) Chrome/9.0.597.15 Safari/534.13",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.186 Safari/535.1",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.54 Safari/535.2",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.36 Safari/535.7",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1063.0 Safari/536.3",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.4 (KHTML like Gecko) Chrome/22.0.1229.79 Safari/537.4",
//   "Mozilla/5.0 (Macintosh; U; Mac OS X Mach-O; en-US; rv:2.0a) Gecko/20040614 Firefox/3.0.0",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.5; en-US; rv:1.9.0.3) Gecko/2008092414 Firefox/3.0.3",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1) Gecko/20090624 Firefox/3.5",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.14) Gecko/20110218 AlexaToolbar/alxf-2.0 Firefox/3.6.14",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.5; en-US; rv:1.9.2.15) Gecko/20110303 Firefox/3.6.15",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0.1) Gecko/20100101 Firefox/4.0.1",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:5.0) Gecko/20100101 Firefox/5.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2; rv:10.0.1) Gecko/20100101 Firefox/10.0.1",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20120813 Firefox/16.0",
//   "Mozilla/4.0 (compatible; MSIE 5.15; Mac_PowerPC)",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US) AppleWebKit/125.4 (KHTML, like Gecko, Safari) OmniWeb/v563.15",
//   "Opera/9.0 (Macintosh; PPC Mac OS X; U; en)",
//   "Opera/9.20 (Macintosh; Intel Mac OS X; U; en)",
//   "Opera/9.64 (Macintosh; PPC Mac OS X; U; en) Presto/2.1.1",
//   "Opera/9.80 (Macintosh; Intel Mac OS X; U; en) Presto/2.6.30 Version/10.61",
//   "Opera/9.80 (Macintosh; Intel Mac OS X 10.4.11; U; en) Presto/2.7.62 Version/11.00",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/125.2 (KHTML, like Gecko) Safari/85.8",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/125.2 (KHTML, like Gecko) Safari/125.8",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; fr-fr) AppleWebKit/312.5 (KHTML, like Gecko) Safari/312.3",
//   "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.31 (KHTML like Gecko) Chrome/26.0.1410.63 Safari/537.31",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 1083) AppleWebKit/537.36 (KHTML like Gecko) Chrome/28.0.1469.0 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1664.3 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2859.0 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.49 Safari/537.36",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:20.0) Gecko/20100101 Firefox/20.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:25.0) Gecko/20100101 Firefox/25.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:47.0) Gecko/20100101 Firefox/47.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:55.0) Gecko/20100101 Firefox/55.0",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Maxthon/4.5.2",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US) AppleWebKit/528.16 (KHTML, like Gecko, Safari/528.16) OmniWeb/v622.8.0.112941",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-US) AppleWebKit/528.16 (KHTML, like Gecko, Safari/528.16) OmniWeb/v622.8.0",
//   "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; fr) Presto/2.9.168 Version/11.52",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/28.0.1750.51",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.82 Safari/537.36 OPR/29.0.1795.41",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_2; en-us) AppleWebKit/531.21.8 (KHTML, like Gecko) Version/4.0.4 Safari/531.21.10",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_5; de-de) AppleWebKit/534.15 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-us) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27",
//   "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7; en-us) AppleWebKit/534.20.8 (KHTML, like Gecko) Version/5.1 Safari/534.20.8",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.13+ (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/536.26.17 (KHTML like Gecko) Version/6.0.2 Safari/536.26.17",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.1 (KHTML like Gecko) Version/7.0.6 Safari/537.78.1",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/10.1 Safari/603.1.30",
//   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1",
//   "Mozilla/5.0 (X11; CrOS i686 2268.111.0) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.4 (KHTML like Gecko) Chrome/22.0.1229.56 Safari/537.4",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1478.0 Safari/537.36",
//   "Mozilla/5.0 (X11; CrOS x86_64 5841.83.0) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.138 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.125 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2166.2 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36",
//   "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2876.0 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3187.0 Safari/537.366",
//   "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3178.0 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.22 (KHTML like Gecko) Ubuntu Chromium/25.0.1364.160 Chrome/25.0.1364.160 Safari/537.22",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/33.0.1750.152 Chrome/33.0.1750.152 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.78 Chrome/60.0.3112.78 Safari/537.36",
//   "Mozilla/4.0 (compatible; Dillo 3.0)",
//   "Mozilla/5.0 (X11; U; Linux i686; en-us) AppleWebKit/528.5 (KHTML, like Gecko, Safari/528.5 ) lt-GtkLauncher",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.32 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.32 Epiphany/3.8.2",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Version/11.0 Safari/604.1 Ubuntu/17.04 (3.24.1-0ubuntu1) Epiphany/3.24.1",
//   "Mozilla/5.0 (X11; Linux i686; rv:16.0) Gecko/20100101 Firefox/16.0",
//   "Mozilla/5.0 (X11; U; Linux i686; rv:19.0) Gecko/20100101 Slackware/13 Firefox/19.0",
//   "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:20.0) Gecko/20100101 Firefox/20.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:20.0) Gecko/20100101 Firefox/20.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:28.0) Gecko/20100101 Firefox/28.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:32.0) Gecko/20100101 Firefox/32.0",
//   "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0",
//   "Mozilla/5.0 (X11; CentOS; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0",
//   "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:40.0) Gecko/20100101 Firefox/40.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:46.0) Gecko/20100101 Firefox/46.0",
//   "Mozilla/5.0 (X11; Linux i686; rv:49.0) Gecko/20100101 Firefox/49.0",
//   "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0",
//   "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0",
//   "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0",
//   "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.166 Safari/537.36 OPR/20.0.1396.73172",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.166 Safari/537.36 OPR/20.0.1396.73172",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 OPR/32.0.1948.25",
//   "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36 OPR/40.0.2308.62",
//   "Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/536.5 (KHTML like Gecko) Chrome/19.0.1084.56 Safari/536.5",
//   "Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.4 (KHTML like Gecko) Chrome/22.0.1229.79 Safari/537.4",
//   "Mozilla/5.0 (X11; NetBSD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36",
//   "Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36",
//   "Mozilla/5.0 (X11; NetBSD x86; en-us) AppleWebKit/666.6+ (KHTML, like Gecko) Chromium/20.0.0000.00 Chrome/20.0.0000.00 Safari/666.6+",
//   "Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.22+ (KHTML, like Gecko) Chromium/17.0.963.56 Chrome/17.0.963.56 Safari/535.22+ Epiphany/2.30.6",
//   "Mozilla/5.0 (X11; U; OpenBSD arm; en-us) AppleWebKit/531.2 (KHTML, like Gecko) Safari/531.2 Epiphany/2.30.0",
//   "Mozilla/5.0 (X11; NetBSD amd64; rv:16.0) Gecko/20121102 Firefox/16.0",
//   "Mozilla/5.0 (X11; OpenBSD amd64; rv:28.0) Gecko/20100101 Firefox/28.0",
//   "Mozilla/5.0 (X11; NetBSD amd64; rv:30.0) Gecko/20100101 Firefox/30.0",
//   "Mozilla/5.0 (X11; OpenBSD amd64; rv:30.0) Gecko/20100101 Firefox/30.0",
//   "Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36",
//   "Mozilla/5.0 (X11; FreeBSD amd64; rv:54.0) Gecko/20100101 Firefox/54.0",
//   "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
// ];
// let userAgentIndex = -1,
//   i = 0;
// let arr = [
//   "https://practice.geeksforgeeks.org/problems/subarray-with-given-sum/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-index/0",
//   "https://practice.geeksforgeeks.org/problems/finding-the-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/longest-valid-parentheses/0",
//   "https://practice.geeksforgeeks.org/problems/jumping-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/connect-nodes-at-same-level/1",
//   "https://practice.geeksforgeeks.org/problems/count-bst-nodes-that-lie-in-a-given-range/1",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
//   "https://practice.geeksforgeeks.org/problems/interleaved-strings/1",
//   "https://practice.geeksforgeeks.org/problems/find-triplets-with-zero-sum/1",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/word-break/0",
//   "https://practice.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/find-largest-word-in-dictionary/0",
//   "https://practice.geeksforgeeks.org/problems/number-of-subsets-and-mean/0",
//   "https://practice.geeksforgeeks.org/problems/subarray-with-given-sum/0",
//   "https://practice.geeksforgeeks.org/problems/find-all-pairs-whose-sum-is-x/0",
//   "https://practice.geeksforgeeks.org/problems/total-decoding-messages/0",
//   "https://practice.geeksforgeeks.org/problems/word-boggle/0",
//   "https://practice.geeksforgeeks.org/problems/activity-selection/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-depth-of-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/implement-strstr/1",
//   "https://practice.geeksforgeeks.org/problems/multiply-two-strings/1",
//   "https://practice.geeksforgeeks.org/problems/k-palindrome/1",
//   "https://practice.geeksforgeeks.org/problems/find-triplets-with-zero-sum/1",
//   "https://practice.geeksforgeeks.org/problems/largest-fibonacci-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/decode-the-pattern/0",
//   "https://practice.geeksforgeeks.org/problems/convert-to-roman-no/1",
//   "https://practice.geeksforgeeks.org/problems/convert-ternary-expression-to-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0",
//   "https://practice.geeksforgeeks.org/problems/k-largest-elements/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
//   "https://practice.geeksforgeeks.org/problems/special-stack/1",
//   "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/stock-span-problem/0",
//   "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
//   "https://practice.geeksforgeeks.org/problems/edit-distance/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k/0",
//   "https://practice.geeksforgeeks.org/problems/pythagorean-triplet/0",
//   "https://practice.geeksforgeeks.org/problems/print-a-binary-tree-in-vertical-order/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/boolean-parenthesization/0",
//   "https://practice.geeksforgeeks.org/problems/largest-number-formed-from-an-array/0",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-difference-between-node-and-its-ancestor/1",
//   "https://practice.geeksforgeeks.org/problems/key-pair/0",
//   "https://practice.geeksforgeeks.org/problems/is-binary-number-multiple-of-3/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/missing-number-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/majority-element/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-rotated-array/0",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/remove-every-kth-node/1",
//   "https://practice.geeksforgeeks.org/problems/merge-2-sorted-linked-list-in-reverse-order/1",
//   "https://practice.geeksforgeeks.org/problems/longest-even-length-substring/0",
//   "https://practice.geeksforgeeks.org/problems/k-largest-elements/0",
//   "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
//   "https://practice.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-rotated-array/0",
//   "https://practice.geeksforgeeks.org/problems/subset-sum-problem/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/sum-tree/1",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1",
//   "https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/set-bits/0",
//   "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/power-of-2/0",
//   "https://practice.geeksforgeeks.org/problems/palindrome/0",
//   "https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/binary-search/1",
//   "https://practice.geeksforgeeks.org/problems/implement-queue-using-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/connect-nodes-at-same-level/1",
//   "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/first-repeating-element/0",
//   "https://practice.geeksforgeeks.org/problems/majority-element/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-rotated-array/0",
//   "https://practice.geeksforgeeks.org/problems/sum-of-middle-elements-of-two-sorted-arrays/0",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-character/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/print-all-nodes-that-dont-have-sibling/1",
//   "https://practice.geeksforgeeks.org/problems/two-mirror-trees/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/trie-insert-and-search/0",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/copy-set-bits-in-range/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/word-boggle/0",
//   "https://practice.geeksforgeeks.org/problems/jumping-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/transform-string/0",
//   "https://practice.geeksforgeeks.org/problems/solve-the-sudoku/0",
//   "https://practice.geeksforgeeks.org/problems/find-nth-root-of-m/0",
//   "https://practice.geeksforgeeks.org/problems/array-pair-sum-divisibility-problem/0",
//   "https://practice.geeksforgeeks.org/problems/largest-zigzag-sequence/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-intervals-overlap/0",
//   "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/maximize-dot-product/0",
//   "https://practice.geeksforgeeks.org/problems/excel-sheet/0",
//   "https://practice.geeksforgeeks.org/problems/probability-of-knight/0",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/rotate-array-by-n-elements/0",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-character/0",
//   "https://practice.geeksforgeeks.org/problems/nth-fibonacci-number/0",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-closest-element-in-bst/1",
//   "https://practice.geeksforgeeks.org/problems/circular-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-the-string/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/largest-prime-factor/0",
//   "https://practice.geeksforgeeks.org/problems/form-coils-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/word-boggle/0",
//   "https://practice.geeksforgeeks.org/problems/largest-product-pallindrome/0",
//   "https://practice.geeksforgeeks.org/problems/surpasser-count/0",
//   "https://practice.geeksforgeeks.org/problems/return-two-prime-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
//   "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
//   "https://practice.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/split-a-circular-linked-list-into-two-halves/1",
//   "https://practice.geeksforgeeks.org/problems/interleaved-strings/1",
//   "https://practice.geeksforgeeks.org/problems/max-sum-without-adjacents/0",
//   "https://practice.geeksforgeeks.org/problems/count-squares/0",
//   "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix/0",
//   "https://practice.geeksforgeeks.org/problems/n-queen-problem/0",
//   "https://practice.geeksforgeeks.org/problems/coin-change/0",
//   "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/stock-buy-and-sell/0",
//   "https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0",
//   "https://practice.geeksforgeeks.org/problems/sum-of-two-numbers-represented-as-arrays/0",
//   "https://practice.geeksforgeeks.org/problems/max-sum-submatrix/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-sum-rectangle/0",
//   "https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1",
//   "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
//   "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/largest-number-in-k-swaps/0",
//   "https://practice.geeksforgeeks.org/problems/k-largest-elements/0",
//   "https://practice.geeksforgeeks.org/problems/word-break/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-highest-occurring-digit-in-prime-numbers-in-a-range/0",
//   "https://practice.geeksforgeeks.org/problems/count-all-possible-paths-from-top-left-to-bottom-right/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-platforms/0",
//   "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
//   "https://practice.geeksforgeeks.org/problems/josephus-problem/1",
//   "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-of-two-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
//   "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/wildcard-pattern-matching/1",
//   "https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
//   "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/next-greater-number-set-digits/0",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/implement-queue-using-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/unique-bsts/0",
//   "https://practice.geeksforgeeks.org/problems/bit-difference/0",
//   "https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1",
//   "https://practice.geeksforgeeks.org/problems/delete-without-head-pointer/1",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
//   "https://practice.geeksforgeeks.org/problems/max-sum-without-adjacents/0",
//   "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
//   "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/coin-change/0",
//   "https://practice.geeksforgeeks.org/problems/frequency-of-array-elements/0",
//   "https://practice.geeksforgeeks.org/problems/row-with-max-1s/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/missing-number-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
//   "https://practice.geeksforgeeks.org/problems/connect-nodes-at-same-level/1",
//   "https://practice.geeksforgeeks.org/problems/k-distance-from-root/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-character/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/minimum-indexed-character/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-difference/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-element-that-appears-once-in-sorted-array/0",
//   "https://practice.geeksforgeeks.org/problems/boolean-matrix-problem/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
//   "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
//   "https://practice.geeksforgeeks.org/problems/consecutive-1s-not-allowed/0",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/get-minimum-element-from-stack/1",
//   "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/connect-nodes-at-same-level/1",
//   "https://practice.geeksforgeeks.org/problems/sum-of-dependencies-in-a-graph/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k/0",
//   "https://practice.geeksforgeeks.org/problems/possible-words-from-phone-digits/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-level-order-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-width-of-tree/1",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/bleak-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/remove-spaces/0",
//   "https://practice.geeksforgeeks.org/problems/second-largest/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-a-number-is-power-of-another-number/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/get-minimum-element-from-stack/1",
//   "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
//   "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/quick-sort/1",
//   "https://practice.geeksforgeeks.org/problems/gcd-of-array/0",
//   "https://practice.geeksforgeeks.org/problems/lcm-and-gcd/0",
//   "https://practice.geeksforgeeks.org/problems/heap-sort/1",
//   "https://practice.geeksforgeeks.org/problems/bubble-sort/1",
//   "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-index/0",
//   "https://practice.geeksforgeeks.org/problems/array-to-bst/0",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/run-length-encoding/1",
//   "https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/infix-to-postfix/0",
//   "https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
//   "https://practice.geeksforgeeks.org/problems/boolean-matrix-problem/0",
//   "https://practice.geeksforgeeks.org/problems/missing-number-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/array-to-bst/0",
//   "https://practice.geeksforgeeks.org/problems/set-bits/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1",
//   "https://practice.geeksforgeeks.org/problems/does-array-represent-heap/0",
//   "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/thief-try-to-excape/0",
//   "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
//   "https://practice.geeksforgeeks.org/problems/insertion-sort/1",
//   "https://practice.geeksforgeeks.org/problems/bubble-sort/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/overlapping-rectangles/0",
//   "https://practice.geeksforgeeks.org/problems/column-name-from-a-given-column-number/0",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-character/0",
//   "https://practice.geeksforgeeks.org/problems/total-decoding-messages/0",
//   "https://practice.geeksforgeeks.org/problems/sum-tree/1",
//   "https://practice.geeksforgeeks.org/problems/get-minimum-element-from-stack/1",
//   "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/stock-buy-and-sell/0",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1",
//   "https://practice.geeksforgeeks.org/problems/check-if-two-arrays-are-equal-or-not/0",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/distinct-palindromic-substrings/0",
//   "https://practice.geeksforgeeks.org/problems/two-water-jug-problem/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-cost-path/0",
//   "https://practice.geeksforgeeks.org/problems/transpose-of-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
//   "https://practice.geeksforgeeks.org/problems/check-mirror-in-n-ary-tree/0",
//   "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-difference/0",
//   "https://practice.geeksforgeeks.org/problems/nuts-and-bolts-problem/0",
//   "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room/0",
//   "https://practice.geeksforgeeks.org/problems/string-formation-from-substring/0",
//   "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/next-permutation/0",
//   "https://practice.geeksforgeeks.org/problems/trailing-zeroes-in-factorial/0",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/fighting-the-darkness/0",
//   "https://practice.geeksforgeeks.org/problems/money-division/0",
//   "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
//   "https://practice.geeksforgeeks.org/problems/pangram-strings/0",
//   "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
//   "https://practice.geeksforgeeks.org/problems/longest-arithmetic-progression/0",
//   "https://practice.geeksforgeeks.org/problems/next-greater-number-set-digits/0",
//   "https://practice.geeksforgeeks.org/problems/number-of-coins/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-two-line-segments-intersect/0",
//   "https://practice.geeksforgeeks.org/problems/two-numbers-with-sum-closest-to-zero/0",
//   "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0",
//   "https://practice.geeksforgeeks.org/problems/smallest-positive-missing-number/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
//   "https://practice.geeksforgeeks.org/problems/find-length-of-loop/1",
//   "https://practice.geeksforgeeks.org/problems/implement-strstr/1",
//   "https://practice.geeksforgeeks.org/problems/min-distance-between-two-given-nodes-of-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/delete-a-node-from-bst/1",
//   "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-bits/0",
//   "https://practice.geeksforgeeks.org/problems/next-permutation/0",
//   "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
//   "https://practice.geeksforgeeks.org/problems/set-bits/0",
//   "https://practice.geeksforgeeks.org/problems/find-prime-numbers-in-a-range/0",
//   "https://practice.geeksforgeeks.org/problems/subsequence-matching/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-each-word-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
//   "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
//   "https://practice.geeksforgeeks.org/problems/leaders-in-an-array/0",
//   "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
//   "https://practice.geeksforgeeks.org/problems/pattern-searching/0",
//   "https://practice.geeksforgeeks.org/problems/implement-atoi/1",
//   "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1",
//   "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/missing-number-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/count-possible-ways-to-construct-buildings/0",
//   "https://practice.geeksforgeeks.org/problems/unsorted-array/0",
//   "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/product-array-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/count-occurences-of-anagrams/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-sub-array/0",
//   "https://practice.geeksforgeeks.org/problems/binary-array-sorting/0",
//   "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
//   "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
//   "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/pairwise-swap-elements-of-a-linked-list-by-swapping-data/1",
//   "https://practice.geeksforgeeks.org/problems/find-the-missing-no-in-string/1",
//   "https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1",
//   "https://practice.geeksforgeeks.org/problems/print-the-pattern-set-1/1",
//   "https://practice.geeksforgeeks.org/problems/print-table/0",
//   "https://practice.geeksforgeeks.org/problems/series-ap/0",
//   "https://practice.geeksforgeeks.org/problems/series-gp/0",
//   "https://practice.geeksforgeeks.org/problems/closest-number/0",
//   "https://practice.geeksforgeeks.org/problems/armstrong-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/sum-of-digit-is-pallindrome-or-not/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-digit/0",
//   "https://practice.geeksforgeeks.org/problems/print-the-kth-digit/0",
//   "https://practice.geeksforgeeks.org/problems/binary-number-to-decimal-number/0",
//   "https://practice.geeksforgeeks.org/problems/jumping-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/gcd-of-two-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/lcm-and-gcd/0",
//   "https://practice.geeksforgeeks.org/problems/add-two-fractions/1",
//   "https://practice.geeksforgeeks.org/problems/gcd-of-array/0",
//   "https://practice.geeksforgeeks.org/problems/factorial/0",
//   "https://practice.geeksforgeeks.org/problems/npr/0",
//   "https://practice.geeksforgeeks.org/problems/ncr/0",
//   "https://practice.geeksforgeeks.org/problems/largest-prime-factor/0",
//   "https://practice.geeksforgeeks.org/problems/perfect-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/pair-cube-count/0",
//   "https://practice.geeksforgeeks.org/problems/find-nth-root-of-m/0",
//   "https://practice.geeksforgeeks.org/problems/prime-number/0",
//   "https://practice.geeksforgeeks.org/problems/sieve-of-eratosthenes/0",
//   "https://practice.geeksforgeeks.org/problems/sum-of-all-prime-numbers-between-1-and-n/0",
//   "https://practice.geeksforgeeks.org/problems/pairs-of-prime-number/0",
//   "https://practice.geeksforgeeks.org/problems/count-squares/0",
//   "https://practice.geeksforgeeks.org/problems/3-divisors/0",
//   "https://practice.geeksforgeeks.org/problems/is-square/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-a-number-is-power-of-another-number/0",
//   "https://practice.geeksforgeeks.org/problems/overlapping-rectangles/0",
//   "https://practice.geeksforgeeks.org/problems/trailing-zeroes-in-factorial/0",
//   "https://practice.geeksforgeeks.org/problems/angle-between-hour-and-minute-hand/0",
//   "https://practice.geeksforgeeks.org/problems/number-of-open-doors/0",
//   "https://practice.geeksforgeeks.org/problems/triangular-number/0",
//   "https://practice.geeksforgeeks.org/problems/nth-even-fibonacci-number/0",
//   "https://practice.geeksforgeeks.org/problems/last-two-digit-fibonacci/0",
//   "https://practice.geeksforgeeks.org/problems/squares-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/day-of-the-week/0",
//   "https://practice.geeksforgeeks.org/problems/operating-an-array/1",
//   "https://practice.geeksforgeeks.org/problems/print-alternate-elements-of-an-array/1",
//   "https://practice.geeksforgeeks.org/problems/find-minimum-and-maximum-element-in-an-array/0",
//   "https://practice.geeksforgeeks.org/problems/second-largest/0",
//   "https://practice.geeksforgeeks.org/problems/sum-of-array-elements/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-an-array/0",
//   "https://practice.geeksforgeeks.org/problems/rotate-array-by-n-elements/0",
//   "https://practice.geeksforgeeks.org/problems/count-of-smaller-elements/0",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicate-elements-from-sorted-array/1",
//   "https://practice.geeksforgeeks.org/problems/count-possible-triangles/0",
//   "https://practice.geeksforgeeks.org/problems/leaders-in-an-array/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-distance-between-two-numbers/1",
//   "https://practice.geeksforgeeks.org/problems/sorted-subsequence-of-size-3/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-sub-array/0",
//   "https://practice.geeksforgeeks.org/problems/majority-element/0",
//   "https://practice.geeksforgeeks.org/problems/wave-array/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-index/0",
//   "https://practice.geeksforgeeks.org/problems/max-sum-path-in-two-arrays/1",
//   "https://practice.geeksforgeeks.org/problems/product-array-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/find-duplicates-in-an-array/1",
//   "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating/0",
//   "https://practice.geeksforgeeks.org/problems/stock-buy-and-sell/0",
//   "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
//   "https://practice.geeksforgeeks.org/problems/pair-with-given-sum-in-a-sorted-array/0",
//   "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
//   "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/1",
//   "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1",
//   "https://practice.geeksforgeeks.org/problems/palindrome-string/0",
//   "https://practice.geeksforgeeks.org/problems/anagram/0",
//   "https://practice.geeksforgeeks.org/problems/anagram-palindrome/0",
//   "https://practice.geeksforgeeks.org/problems/upper-case-conversion/0",
//   "https://practice.geeksforgeeks.org/problems/sort-the-string-in-descending-order/0",
//   "https://practice.geeksforgeeks.org/problems/merge-two-strings/0",
//   "https://practice.geeksforgeeks.org/problems/save-ironman/0",
//   "https://practice.geeksforgeeks.org/problems/good-or-bad-string/0",
//   "https://practice.geeksforgeeks.org/problems/urlify-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/extract-maximum/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/implement-strstr/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-strings-are-rotations-of-each-other-or-not/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-two-strings-are-k-anagrams-or-not/1",
//   "https://practice.geeksforgeeks.org/problems/uncommon-characters/0",
//   "https://practice.geeksforgeeks.org/problems/anagram-of-string/1",
//   "https://practice.geeksforgeeks.org/problems/find-first-repeated-character/0",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-character/0",
//   "https://practice.geeksforgeeks.org/problems/longest-distinct-characters-in-string/0",
//   "https://practice.geeksforgeeks.org/problems/longest-palindromic-substring-in-linear-time/1",
//   "https://practice.geeksforgeeks.org/problems/find-k-th-character-in-string/0",
//   "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
//   "https://practice.geeksforgeeks.org/problems/add-binary-strings/0",
//   "https://practice.geeksforgeeks.org/problems/multiply-two-strings/1",
//   "https://practice.geeksforgeeks.org/problems/nearest-multiple-of-10/0",
//   "https://practice.geeksforgeeks.org/problems/searching-a-number/0",
//   "https://practice.geeksforgeeks.org/problems/facing-the-sun/0",
//   "https://practice.geeksforgeeks.org/problems/magnet-array-problem/0",
//   "https://practice.geeksforgeeks.org/problems/binary-search/1",
//   "https://practice.geeksforgeeks.org/problems/floor-in-a-sorted-array/0",
//   "https://practice.geeksforgeeks.org/problems/number-of-occurrence/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-rotated-array/0",
//   "https://practice.geeksforgeeks.org/problems/missing-number/0",
//   "https://practice.geeksforgeeks.org/problems/missing-element-of-ap/0",
//   "https://practice.geeksforgeeks.org/problems/square-root/1",
//   "https://practice.geeksforgeeks.org/problems/find-transition-point/1",
//   "https://practice.geeksforgeeks.org/problems/last-index-of-1/0",
//   "https://practice.geeksforgeeks.org/problems/peak-element/1",
//   "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0",
//   "https://practice.geeksforgeeks.org/problems/common-elements/0",
//   "https://practice.geeksforgeeks.org/problems/smallest-positive-missing-number/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-an-array-is-sorted/0",
//   "https://practice.geeksforgeeks.org/problems/binary-array-sorting/0",
//   "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
//   "https://practice.geeksforgeeks.org/problems/bubble-sort/1",
//   "https://practice.geeksforgeeks.org/problems/insertion-sort/1",
//   "https://practice.geeksforgeeks.org/problems/selection-sort/1",
//   "https://practice.geeksforgeeks.org/problems/quick-sort/1",
//   "https://practice.geeksforgeeks.org/problems/merge-sort/1",
//   "https://practice.geeksforgeeks.org/problems/sort-the-half-sorted/0",
//   "https://practice.geeksforgeeks.org/problems/relative-sorting/0",
//   "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-swaps/1",
//   "https://practice.geeksforgeeks.org/problems/sorting-elements-of-an-array-by-frequency/0",
//   "https://practice.geeksforgeeks.org/problems/triplet-family/1",
//   "https://practice.geeksforgeeks.org/problems/count-the-triplets/0",
//   "https://practice.geeksforgeeks.org/problems/find-distinct-elements/0",
//   "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
//   "https://practice.geeksforgeeks.org/problems/nuts-and-bolts-problem/0",
//   "https://practice.geeksforgeeks.org/problems/frequency-of-array-elements/0",
//   "https://practice.geeksforgeeks.org/problems/check-if-two-arrays-are-equal-or-not/0",
//   "https://practice.geeksforgeeks.org/problems/first-element-to-occur-k-times/0",
//   "https://practice.geeksforgeeks.org/problems/in-first-but-second/0",
//   "https://practice.geeksforgeeks.org/problems/non-repeating-element/0",
//   "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
//   "https://practice.geeksforgeeks.org/problems/winner-of-an-election-where-votes-are-represented-as-candidate-names/0",
//   "https://practice.geeksforgeeks.org/problems/key-pair/0",
//   "https://practice.geeksforgeeks.org/problems/count-distinct-pairs-with-difference-k/0",
//   "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum/0",
//   "https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/a-simple-fraction/0",
//   "https://practice.geeksforgeeks.org/problems/largest-fibonacci-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/transpose-of-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/print-matrix-in-snake-pattern/0",
//   "https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/is-sudoku-valid/0",
//   "https://practice.geeksforgeeks.org/problems/count-zeros-in-a-sorted-matrix/1",
//   "https://practice.geeksforgeeks.org/problems/squares-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/boolean-matrix-problem/0",
//   "https://practice.geeksforgeeks.org/problems/search-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/row-with-max-1s/0",
//   "https://practice.geeksforgeeks.org/problems/count-pairs-sum-in-matrices/0",
//   "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/print-pattern/0",
//   "https://practice.geeksforgeeks.org/problems/handshakes/0",
//   "https://practice.geeksforgeeks.org/problems/tower-of-hanoi/0",
//   "https://practice.geeksforgeeks.org/problems/josephus-problem/1",
//   "https://practice.geeksforgeeks.org/problems/recursively-remove-all-adjacent-duplicates/0",
//   "https://practice.geeksforgeeks.org/problems/possible-words-from-phone-digits/0",
//   "https://practice.geeksforgeeks.org/problems/flood-fill-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
//   "https://practice.geeksforgeeks.org/problems/power-of-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/the-nth-fibonnaci/0",
//   "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-median/0",
//   "https://practice.geeksforgeeks.org/problems/karatsuba-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/the-painters-partition-problem/0",
//   "https://practice.geeksforgeeks.org/problems/convex-hull/0",
//   "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
//   "https://practice.geeksforgeeks.org/problems/print-linked-list-elements/1",
//   "https://practice.geeksforgeeks.org/problems/count-nodes-of-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/node-at-a-given-index-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/delete-a-node-in-single-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/remove-every-kth-node/1",
//   "https://practice.geeksforgeeks.org/problems/delete-n-nodes-after-m-nodes-of-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/delete-without-head-pointer/1",
//   "https://practice.geeksforgeeks.org/problems/rearrange-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list/0",
//   "https://practice.geeksforgeeks.org/problems/reorder-list/1",
//   "https://practice.geeksforgeeks.org/problems/polynomial-addition/1",
//   "https://practice.geeksforgeeks.org/problems/insert-in-a-sorted-list/1",
//   "https://practice.geeksforgeeks.org/problems/pairwise-swap-elements-of-a-linked-list-by-swapping-data/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
//   "https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1",
//   "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/given-a-linked-list-of-0s-1s-and-2s-sort-it/1",
//   "https://practice.geeksforgeeks.org/problems/circular-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/find-length-of-loop/1",
//   "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1",
//   "https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/multiply-two-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/intersection-of-two-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/union-of-two-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/insert-a-node-in-doubly-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/delete-node-in-doubly-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/circular-linked-list-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/split-a-circular-linked-list-into-two-halves/1",
//   "https://practice.geeksforgeeks.org/problems/insert-in-sorted-way-in-a-sorted-dll/1",
//   "https://practice.geeksforgeeks.org/problems/quicksort-on-doubly-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/merge-sort-on-doubly-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/rotate-doubly-linked-list-by-p-nodes/1",
//   "https://practice.geeksforgeeks.org/problems/xor-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1",
//   "https://practice.geeksforgeeks.org/problems/implement-stack-using-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
//   "https://practice.geeksforgeeks.org/problems/reverse-a-string-using-stack/1",
//   "https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1",
//   "https://practice.geeksforgeeks.org/problems/special-stack/1",
//   "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1",
//   "https://practice.geeksforgeeks.org/problems/stock-span-problem/0",
//   "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
//   "https://practice.geeksforgeeks.org/problems/immediate-smaller-element/0",
//   "https://practice.geeksforgeeks.org/problems/longest-valid-parentheses/0",
//   "https://practice.geeksforgeeks.org/problems/implement-queue-using-linked-list/1",
//   "https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1",
//   "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
//   "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1",
//   "https://practice.geeksforgeeks.org/problems/circular-tour/1",
//   "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/equilibrium-point/0",
//   "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
//   "https://practice.geeksforgeeks.org/problems/longest-sub-array-with-sum-k/0",
//   "https://practice.geeksforgeeks.org/problems/longest-subarray-with-sum-divisible-by-k/0",
//   "https://practice.geeksforgeeks.org/problems/largest-subarray-of-0s-and-1s/1",
//   "https://practice.geeksforgeeks.org/problems/longest-span-with-same-sum-in-two-binary-arrays/0",
//   "https://practice.geeksforgeeks.org/problems/max-sum-subarray-of-size-k/0",
//   "https://practice.geeksforgeeks.org/problems/count-distinct-elements-in-every-window/1",
//   "https://practice.geeksforgeeks.org/problems/subarray-with-given-sum/0",
//   "https://practice.geeksforgeeks.org/problems/help-nobita/0",
//   "https://practice.geeksforgeeks.org/problems/flip-bits/0",
//   "https://practice.geeksforgeeks.org/problems/game-of-xor/0",
//   "https://practice.geeksforgeeks.org/problems/find-position-of-set-bit/0",
//   "https://practice.geeksforgeeks.org/problems/swap-all-odd-and-even-bits/0",
//   "https://practice.geeksforgeeks.org/problems/power-of-2/0",
//   "https://practice.geeksforgeeks.org/problems/find-the-odd-occurence/0",
//   "https://practice.geeksforgeeks.org/problems/missing-number-in-array/0",
//   "https://practice.geeksforgeeks.org/problems/counting-elements-in-two-arrays/1",
//   "https://practice.geeksforgeeks.org/problems/reverse-bits/0",
//   "https://practice.geeksforgeeks.org/problems/set-bits/0",
//   "https://practice.geeksforgeeks.org/problems/power-set/0",
//   "https://practice.geeksforgeeks.org/problems/inorder-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/preorder-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/postorder-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/count-leaves-in-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/children-sum-parent/1",
//   "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1",
//   "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-path-sum/1",
//   "https://practice.geeksforgeeks.org/problems/level-order-traversal-line-by-line/1",
//   "https://practice.geeksforgeeks.org/problems/tree-from-postorder-and-inorder/1",
//   "https://practice.geeksforgeeks.org/problems/construct-tree-1/1",
//   "https://practice.geeksforgeeks.org/problems/connect-nodes-at-same-level/1",
//   "https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1",
//   "https://practice.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1",
//   "https://practice.geeksforgeeks.org/problems/leaves-to-dll/1",
//   "https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1",
//   "https://practice.geeksforgeeks.org/problems/binary-tree-to-cdll/1",
//   "https://practice.geeksforgeeks.org/problems/search-a-node-in-bst/1",
//   "https://practice.geeksforgeeks.org/problems/insert-a-node-in-a-bst/1",
//   "https://practice.geeksforgeeks.org/problems/delete-a-node-from-bst/1",
//   "https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1",
//   "https://practice.geeksforgeeks.org/problems/inorder-traversal-and-bst/0",
//   "https://practice.geeksforgeeks.org/problems/count-bst-nodes-that-lie-in-a-given-range/1",
//   "https://practice.geeksforgeeks.org/problems/add-all-greater-values-to-every-node-in-a-bst/1",
//   "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1",
//   "https://practice.geeksforgeeks.org/problems/closest-neighbor-in-bst/1",
//   "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1",
//   "https://practice.geeksforgeeks.org/problems/convert-level-order-traversal-to-bst/1",
//   "https://practice.geeksforgeeks.org/problems/normal-bst-to-balanced-bst/1",
//   "https://practice.geeksforgeeks.org/problems/find-a-pair-with-given-target-in-bst/1",
//   "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
//   "https://practice.geeksforgeeks.org/problems/fixed-two-nodes-of-a-bst/1",
//   "https://practice.geeksforgeeks.org/problems/median-of-bst/1",
//   "https://practice.geeksforgeeks.org/topics/Binary%20Search%20Tree",
//   "https://practice.geeksforgeeks.org/problems/unique-bsts/0",
//   "https://practice.geeksforgeeks.org/problems/array-to-bst/0",
//   "https://practice.geeksforgeeks.org/problems/preorder-traversal-and-bst/0",
//   "https://practice.geeksforgeeks.org/problems/preorder-to-postorder/0",
//   "https://practice.geeksforgeeks.org/problems/print-leaf-nodes-from-preorder-traversal-of-bst/0",
//   "https://practice.geeksforgeeks.org/problems/three-numbers-sum-equal-to-0/1",
//   "https://practice.geeksforgeeks.org/problems/merge-two-bst-s/1",
//   "https://practice.geeksforgeeks.org/problems/largest-bst/1",
//   "https://practice.geeksforgeeks.org/problems/operations-on-binary-min-heap/1",
//   "https://practice.geeksforgeeks.org/problems/height-of-heap/0",
//   "https://practice.geeksforgeeks.org/problems/heap-sort/1",
//   "https://practice.geeksforgeeks.org/problems/nearly-sorted-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/k-largest-elements/0",
//   "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
//   "https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1",
//   "https://practice.geeksforgeeks.org/problems/print-adjacency-list/0",
//   "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
//   "https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1",
//   "https://practice.geeksforgeeks.org/problems/find-whether-path-exist/0",
//   "https://practice.geeksforgeeks.org/problems/knight-walk/0",
//   "https://practice.geeksforgeeks.org/problems/snake-and-ladder-problem/0",
//   "https://practice.geeksforgeeks.org/problems/bipartite-graph/1",
//   "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1",
//   "https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1",
//   "https://practice.geeksforgeeks.org/problems/rotten-oranges/0",
//   "https://practice.geeksforgeeks.org/problems/topological-sort/1",
//   "https://practice.geeksforgeeks.org/problems/shortest-source-to-destination-path/0",
//   "https://practice.geeksforgeeks.org/problems/transitive-closure-of-a-graph/0",
//   "https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1",
//   "https://practice.geeksforgeeks.org/problems/fractional-knapsack/0",
//   "https://practice.geeksforgeeks.org/problems/largest-number-with-given-sum/0",
//   "https://practice.geeksforgeeks.org/problems/activity-selection/0",
//   "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-platforms/0",
//   "https://practice.geeksforgeeks.org/problems/-minimum-number-of-coins/0",
//   "https://practice.geeksforgeeks.org/problems/job-sequencing-problem/0",
//   "https://practice.geeksforgeeks.org/problems/minimize-the-heights/0",
//   "https://practice.geeksforgeeks.org/problems/huffman-encoding/0",
//   "https://practice.geeksforgeeks.org/problems/huffman-decoding-1/1",
//   "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1",
//   "https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1",
//   "https://practice.geeksforgeeks.org/problems/print-first-n-fibonacci-numbers/0",
//   "https://practice.geeksforgeeks.org/problems/count-ways-to-reach-the-nth-stair/0",
//   "https://practice.geeksforgeeks.org/problems/cutted-segments/0",
//   "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
//   "https://practice.geeksforgeeks.org/problems/stickler-theif/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
//   "https://practice.geeksforgeeks.org/problems/total-decoding-messages/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-cost-path/0",
//   "https://practice.geeksforgeeks.org/problems/coin-change/0",
//   "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/consecutive-1s-not-allowed/0",
//   "https://practice.geeksforgeeks.org/problems/edit-distance/0",
//   "https://practice.geeksforgeeks.org/problems/rod-cutting/0",
//   "https://practice.geeksforgeeks.org/problems/champagne-overflow/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-tip-calculator/0",
//   "https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/max-length-chain/1",
//   "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
//   "https://practice.geeksforgeeks.org/problems/maximum-tip-calculator/0",
//   "https://practice.geeksforgeeks.org/problems/interleaved-strings/1",
//   "https://practice.geeksforgeeks.org/problems/longest-palindromic-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/wildcard-pattern-matching/1",
//   "https://practice.geeksforgeeks.org/problems/box-stacking/1",
//   "https://practice.geeksforgeeks.org/problems/longest-bitonic-subsequence/0",
//   "https://practice.geeksforgeeks.org/problems/minimum-sum-partition/0",
//   "https://practice.geeksforgeeks.org/problems/largest-square-formed-in-a-matrix/0",
//   "https://practice.geeksforgeeks.org/problems/word-break/0",
//   "https://practice.geeksforgeeks.org/problems/brackets-in-matrix-chain-multiplication/0",
//   "https://practice.geeksforgeeks.org/problems/special-keyboard/0",
//   "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
//   "https://practice.geeksforgeeks.org/problems/tom-and-jerry/0",
//   "https://practice.geeksforgeeks.org/problems/rat-maze-with-multiple-jumps/0",
//   "https://practice.geeksforgeeks.org/problems/coins-and-game/0",
//   "https://practice.geeksforgeeks.org/problems/hamiltonian-path/0",
//   "https://practice.geeksforgeeks.org/problems/solve-the-sudoku/0",
//   "https://practice.geeksforgeeks.org/problems/combination-sum-part-2/0",
//   "https://practice.geeksforgeeks.org/problems/combination-sum/0",
//   "https://practice.geeksforgeeks.org/problems/subsets/0",
//   "https://practice.geeksforgeeks.org/problems/largest-number-in-k-swaps/0",
//   "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0",
//   "https://practice.geeksforgeeks.org/problems/black-and-white/0",
//   "https://practice.geeksforgeeks.org/problems/trie-insert-and-search/0",
//   "https://practice.geeksforgeeks.org/problems/trie-delete/1",
//   "https://practice.geeksforgeeks.org/problems/unique-rows-in-boolean-matrix/1",
//   "https://practice.geeksforgeeks.org/problems/count-of-distinct-substrings/1",
//   "https://practice.geeksforgeeks.org/problems/word-boggle/0",
//   "https://www.geeksforgeeks.org/trie-insert-and-search",
//   "https://practice.geeksforgeeks.org/problems/minimum-shift-for-longest-common-prefix/0",
//   "https://practice.geeksforgeeks.org/problems/implement-atoi/1",
//   "https://practice.geeksforgeeks.org/problems/two-numbers-with-sum-closest-to-zero/0",
//   "https://www.geeksforgeeks.org/smallest-greater-elements-in-whole-array",
//   "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
//   "https://practice.geeksforgeeks.org/problems/find-triplets-with-zero-sum/1",
//   "https://practice.geeksforgeeks.org/problems/counting-elements-in-two-arrays/1",
//   "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
//   "https://practice.geeksforgeeks.org/problems/maximum-difference/1",
//   "https://practice.geeksforgeeks.org/problems/circle-of-strings/0",
//   "https://practice.geeksforgeeks.org/problems/word-break-part-2/0",
//   "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
//   "https://practice.geeksforgeeks.org/problems/design-a-tiny-url-or-url-shortener/0",
//   "https://practice.geeksforgeeks.org/problems/lru-cache/1",
// ];
// setInterval(() => {
// userAgentIndex++;
// if (userAgentIndex >= agent.length) userAgentIndex = 0;
//   trackingFun();
// }, 500);
// async function fetchHTML(url) {
//   try {
//     const { data } = await axios.get(url, {
//       headers: {
//         "User-Agent": `"${agent[userAgentIndex]}"`,
//       },
//     });
//     return cheerio.load(data);
//   } catch (error) {
//     console.log(error.message);
//   }
// }
const arr = [...sheet.problemsOfTheDay];
// const ds = [];
// let i = 0;
// const trackingFun = async () => {
//   if (i < arr.length) {
//     const $ = await fetchHTML(arr[i]);
//     if ($) {
//       if (arr[i].includes("practice.geeksforgeeks.org")) {
//         let diff = $(".problem-tab__problem-level").text();
//         let name = $(".problem-tab__name").text().trim();
//         let topic = $("#topicTags").text().trim();
//         let top = topic.split("     ");
//         console.log(arr[i], diff, name, top);
//         addData({
//           url: `${arr[i]}`,
//           title: `${name}`,
//           difficulty: `${diff}`,
//           topic: top,
//         });
//         // addData(ds);
//       }
//     }
//   }
//   i++;
// if (i < arr.length) {
//   if (ds.find((val) => val.url == arr[i].url) == undefined) {
//     ds.push(arr[i]);
//     addData(arr[i]);
//   }
// } else console.log("limit reached");
// i++;
// };
// for (let i = 0; i < arr.length; i++) console.log(arr[i].title.length == 0 && i);
