sheet = {};
sheet.frazsheet = [
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/two-sum/",
    title: "Two sum",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    title: "Best time to buy and sell stock",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-sorted-array/",
    title: "Merge sorted array",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/move-zeroes/",
    title: "Move zeroes",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
    title: "Best time to buy and sell stock ii",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/running-sum-of-1d-array/",
    title: "Running sum of 1d array",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-pivot-index/",
    title: "Find pivot index",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/majority-element/",
    title: "Majority element",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/squares-of-a-sorted-array/",
    title: "Squares of a sorted array",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/fibonacci-number/",
    title: "Fibonacci number",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/pascals-triangle/",
    title: "Pascals triangle",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-intervals/",
    title: "Merge intervals",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    title: "Remove duplicates from sorted array",
    difficulty: "1",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/3sum/",
    title: "3sum",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    title: "Product of array except self",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
    title: "Insert delete getrandom o1",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subarray-sum-equals-k/",
    title: "Subarray sum equals k",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/spiral-matrix/",
    title: "Spiral matrix",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/container-with-most-water/",
    title: "Container with most water",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotate-image/",
    title: "Rotate image",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/next-permutation/",
    title: "Next permutation",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-search/",
    title: "Word search",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/3sum-closest/",
    title: "3sum closest",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/game-of-life/",
    title: "Game of life",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/",
    title: "Pairs of songs with total durations divisible by 60",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/4sum/",
    title: "4sum",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    title: "Find the duplicate number",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/combination-sum/",
    title: "Combination sum",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/jump-game-ii/",
    title: "Jump game ii",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts/",
    title: "Maximum area of a piece of cake after horizontal and vertical cuts",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/",
    title: "Maximum points you can obtain from cards",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-area-of-island/",
    title: "Max area of island",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
    title: "Find all duplicates in an array",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/k-diff-pairs-in-an-array/",
    title: "K diff pairs in an array",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subsets/",
    title: "Subsets",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/invalid-transactions/",
    title: "Invalid transactions",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/jump-game/",
    title: "Jump game",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subarray-sums-divisible-by-k/",
    title: "Subarray sums divisible by k",
    difficulty: "2",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/first-missing-positive/",
    title: "First missing positive",
    difficulty: "3",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    title: "Largest rectangle in histogram",
    difficulty: "3",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/",
    title: "Insert delete getrandom o1 duplicates allowed",
    difficulty: "3",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
    title: "Best time to buy and sell stock iii",
    difficulty: "3",
  },
  {
    topic: ["Array"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-value-of-equation/",
    title: "Max value of equation",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-subarray/",
    title: "Maximum subarray",
    difficulty: "1",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/climbing-stairs",
    title: "/",
    difficulty: "1",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/divisor-game/",
    title: "Divisor game",
    difficulty: "1",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/counting-bits/",
    title: "Counting bits",
    difficulty: "1",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/decode-ways/",
    title: "Decode ways",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-break/",
    title: "Word break",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/delete-and-earn/",
    title: "Delete and earn",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximal-square/",
    title: "Maximal square",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/coin-change/",
    title: "Coin change",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-product-subarray/",
    title: "Maximum product subarray",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/",
    title: "Maximum length of repeated subarray",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindromic-substrings/",
    title: "Palindromic substrings",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/house-robber/",
    title: "House robber",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/continuous-subarray-sum/",
    title: "Continuous subarray sum",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/knight-dialer/",
    title: "Knight dialer",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
    title: "Longest increasing subsequence",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/unique-paths/",
    title: "Unique paths",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/",
    title: "Count square submatrices with all ones",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
    title: "Range sum query 2d immutable",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-arithmetic-subsequence/",
    title: "Longest arithmetic subsequence",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/trapping-rain-water/",
    title: "Trapping rain water",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-break-ii/",
    title: "Word break ii",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/regular-expression-matching/",
    title: "Regular expression matching",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximal-rectangle/",
    title: "Maximal rectangle",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-valid-parentheses/",
    title: "Longest valid parentheses",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/edit-distance/",
    title: "Edit distance",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/",
    title: "Minimum difficulty of a job schedule",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/frog-jump/",
    title: "Frog jump",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
    title: "Best time to buy and sell stock iv",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/burst-balloons/",
    title: "Burst balloons",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-cost-to-merge-stones/",
    title: "Minimum cost to merge stones",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
    title: "Minimum insertion steps to make a string palindrome",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/roman-to-integer/",
    title: "Roman to integer",
    difficulty: "1",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/valid-palindrome-ii/",
    title: "Valid palindrome ii",
    difficulty: "1",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
    title: "Minimum cost to cut a stick",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-strstr/",
    title: "Implement strstr",
    difficulty: "1",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-common-prefix/",
    title: "Longest common prefix",
    difficulty: "1",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/add-strings/",
    title: "Add strings",
    difficulty: "1",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    title: "Longest substring without repeating characters",
    difficulty: "2",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-different-palindromic-subsequences/",
    title: "Count different palindromic subsequences",
    difficulty: "3",
  },
  {
    topic: ["Dynamic Programming"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/super-egg-drop/",
    title: "Super egg drop",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
    title: "Minimum remove to make valid parentheses",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    title: "Longest palindromic substring",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/group-anagrams/",
    title: "Group anagrams",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/generate-parentheses/",
    title: "Generate parentheses",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/basic-calculator-ii/",
    title: "Basic calculator ii",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/integer-to-roman/",
    title: "Integer to roman",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-words-in-a-string/",
    title: "Reverse words in a string",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/simplify-path/",
    title: "Simplify path",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/zigzag-conversion/",
    title: "Zigzag conversion",
    difficulty: "2",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/text-justification/",
    title: "Text justification",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/integer-to-english-words/",
    title: "Integer to english words",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-window-substring/",
    title: "Minimum window substring",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/valid-number/",
    title: "Valid number",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/distinct-subsequences/",
    title: "Distinct subsequences",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/",
    title: "Smallest range covering elements from k lists",
    difficulty: "3",
  },
  {
    topic: ["String"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
    title: "Substring with concatenation of all words",
    difficulty: "3",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-integer/",
    title: "Reverse integer",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/add-binary/",
    title: "Add binary",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindrome-number/",
    title: "Palindrome number",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements/",
    title: "Minimum moves to equal array elements",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/happy-number/",
    title: "Happy number",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/excel-sheet-column-title/",
    title: "Excel sheet column title",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/missing-number/",
    title: "Missing number",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-product-of-three-numbers/",
    title: "Maximum product of three numbers",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/power-of-two/",
    title: "Power of two",
    difficulty: "1",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/encode-and-decode-tinyurl/",
    title: "Encode and decode tinyurl",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/string-to-integer-atoi/",
    title: "String to integer atoi",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/multiply-strings/",
    title: "Multiply strings",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/angle-between-hands-of-a-clock/",
    title: "Angle between hands of a clock",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/integer-break/",
    title: "Integer break",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/valid-square/",
    title: "Valid square",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/basic-calculator/",
    title: "Basic calculator",
    difficulty: "3",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/the-kth-factor-of-n/",
    title: "The kth factor of n",
    difficulty: "2",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-points-on-a-line/",
    title: "Max points on a line",
    difficulty: "3",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/permutation-sequence/",
    title: "Permutation sequence",
    difficulty: "3",
  },
  {
    topic: ["Math"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-digit-one/",
    title: "Number of digit one",
    difficulty: "3",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/task-scheduler/",
    title: "Task scheduler",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/gas-station/",
    title: "Gas station",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-deletion-cost-to-avoid-repeating-letters/",
    title: "Minimum deletion cost to avoid repeating letters",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/",
    title: "Maximum number of events that can be attended",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/",
    title: "Minimum deletions to make character frequencies unique",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-k-digits/",
    title: "Remove k digits",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/",
    title: "Restore the array from adjacent pairs",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/non-overlapping-intervals/",
    title: "Non overlapping intervals",
    difficulty: "2",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/candy/",
    title: "Candy",
    difficulty: "3",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/",
    title: "Minimum number of taps to open to water a garden",
    difficulty: "3",
  },
  {
    topic: ["Greedy"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/create-maximum-number/",
    title: "Create maximum number",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    title: "Letter combinations of a phone number",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/course-schedule-ii/",
    title: "Course schedule ii",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/decode-string/",
    title: "Decode string",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-provinces/",
    title: "Number of provinces",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/shortest-bridge/",
    title: "Shortest bridge",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/clone-graph/",
    title: "Clone graph",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/all-paths-from-source-to-target/",
    title: "All paths from source to target",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/house-robber-iii/",
    title: "House robber iii",
    difficulty: "2",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/critical-connections-in-a-network/",
    title: "Critical connections in a network",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-invalid-parentheses/",
    title: "Remove invalid parentheses",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    title: "Longest increasing path in a matrix",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/concatenated-words/",
    title: "Concatenated words",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/making-a-large-island/",
    title: "Making a large island",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/contain-virus/",
    title: "Contain virus",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/24-game/",
    title: "24 game",
    difficulty: "3",
  },
  {
    topic: ["Dfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-boxes/",
    title: "Remove boxes",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/diameter-of-binary-tree/",
    title: "Diameter of binary tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/invert-binary-tree/",
    title: "Invert binary tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subtree-of-another-tree/",
    title: "Subtree of another tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/range-sum-of-bst/",
    title: "Range sum of bst",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/symmetric-tree/",
    title: "Symmetric tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
    title: "Convert sorted array to binary search tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-two-binary-trees/",
    title: "Merge two binary trees",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    title: "Maximum depth of binary tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-paths/",
    title: "Binary tree paths",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/same-tree/",
    title: "Same tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    title: "Lowest common ancestor of a binary search tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/path-sum/",
    title: "Path sum",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sum-of-left-leaves/",
    title: "Sum of left leaves",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
    title: "Minimum absolute difference in bst",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/balanced-binary-tree/",
    title: "Balanced binary tree",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-inorder-traversal/   (USING Stack TOO)",
    title: "/",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
    title: "Count good nodes in binary tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    title: "Lowest common ancestor of a binary tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
    title: "Binary tree right side view",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/",
    title: "All nodes distance k in binary tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
    title: "Validate binary search tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    title: "Binary tree zigzag level order traversal",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/path-sum-iii/",
    title: "Path sum iii",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    title: "Binary tree level order traversal",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-search-tree-iterator/",
    title: "Binary search tree iterator",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/",
    title: "Construct binary tree from preorder and postorder traversal",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
    title: "Flatten binary tree to linked list",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    title: "Serialize and deserialize binary tree",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/unique-binary-search-trees/",
    title: "Unique binary search trees",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/redundant-connection/",
    title: "Redundant connection",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/unique-binary-search-trees-ii/",
    title: "Unique binary search trees ii",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/recover-binary-search-tree/",
    title: "Recover binary search tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    title: "Kth smallest element in a bst",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-width-of-binary-tree/",
    title: "Maximum width of binary tree",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    title: "Binary tree maximum path sum",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
    title: "Populating next right pointers in each node",
    difficulty: "2",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
    title: "Vertical order traversal of a binary tree",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-cameras/",
    title: "Binary tree cameras",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sum-of-distances-in-tree/",
    title: "Sum of distances in tree",
    difficulty: "3",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-ways-to-reconstruct-a-tree/",
    title: "Number of ways to reconstruct a tree",
    difficulty: "3",
  },
  {
    topic: ["Hashing"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/verifying-an-alien-dictionary/",
    title: "Verifying an alien dictionary",
    difficulty: "1",
  },
  {
    topic: ["Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/redundant-connection-ii/",
    title: "Redundant connection ii",
    difficulty: "3",
  },
  {
    topic: ["Hashing"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-hashmap/",
    title: "Design hashmap",
    difficulty: "1",
  },
  {
    topic: ["Hashing"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
    title: "Top k frequent elements",
    difficulty: "2",
  },
  {
    topic: ["Hashing"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-twitter/",
    title: "Design twitter",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sqrtx/",
    title: "Sqrtx",
    difficulty: "1",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-search/",
    title: "Binary search",
    difficulty: "1",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/",
    title: "Count negative numbers in a sorted matrix",
    difficulty: "1",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/peak-index-in-a-mountain-array/",
    title: "Peak index in a mountain array",
    difficulty: "1",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/time-based-key-value-store/",
    title: "Time based key value store",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    title: "Search in rotated sorted array",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/powx-n/",
    title: "Powx n",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    title: "Find first and last position of element in sorted array",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-peak-element/",
    title: "Find peak element",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-a-2d-matrix/",
    title: "Search a 2d matrix",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/divide-two-integers/",
    title: "Divide two integers",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/",
    title: "Minimum limit of balls in a bag",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
    title: "Capacity to ship packages within d days",
    difficulty: "2",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    title: "Median of two sorted arrays",
    difficulty: "3",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
    title: "Count of smaller numbers after self",
    difficulty: "3",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/",
    title: "Max sum of rectangle no larger than k",
    difficulty: "3",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/split-array-largest-sum/",
    title: "Split array largest sum",
    difficulty: "3",
  },
  {
    topic: ["Binary Search"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
    title: "Shortest subarray with sum at least k",
    difficulty: "3",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-islands/",
    title: "Number of islands",
    difficulty: "2",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotting-oranges/",
    title: "Rotting oranges",
    difficulty: "2",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/snakes-and-ladders/",
    title: "Snakes and ladders",
    difficulty: "2",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-jumps-to-reach-home/",
    title: "Minimum jumps to reach home",
    difficulty: "2",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/is-graph-bipartite/",
    title: "Is graph bipartite",
    difficulty: "2",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-ladder/",
    title: "Word ladder",
    difficulty: "3",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-ladder-ii/",
    title: "Word ladder ii",
    difficulty: "3",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/cut-off-trees-for-golf-event/",
    title: "Cut off trees for golf event",
    difficulty: "3",
  },
  {
    topic: ["Bfs"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/",
    title: "Reachable nodes in subdivided graph",
    difficulty: "3",
  },
  {
    topic: ["Two Pointer"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/partition-labels/",
    title: "Partition labels",
    difficulty: "3",
  },
  {
    topic: ["Two Pointer"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sort-colors/",
    title: "Sort colors",
    difficulty: "2",
  },
  {
    topic: ["Two Pointer"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    title: "Longest repeating character replacement",
    difficulty: "3",
  },
  {
    topic: ["Two Pointer"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-number-of-visible-points/",
    title: "Maximum number of visible points",
    difficulty: "2",
  },
  {
    topic: ["Two Pointer"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subarrays-with-k-different-integers/",
    title: "Subarrays with k different integers",
    difficulty: "3",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindrome-partitioning/",
    title: "Palindrome partitioning",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/combination-sum-ii/",
    title: "Combination sum ii",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/combinations/",
    title: "Combinations",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/permutations-ii/",
    title: "Permutations ii",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subsets-ii/",
    title: "Subsets ii",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/beautiful-arrangement/",
    title: "Beautiful arrangement",
    difficulty: "2",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-search-ii/",
    title: "Word search ii",
    difficulty: "3",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sudoku-solver/",
    title: "Sudoku solver",
    difficulty: "3",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/n-queens/",
    title: "N queens",
    difficulty: "3",
  },
  {
    topic: ["Backtracking"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/unique-paths-iii/",
    title: "Unique paths iii",
    difficulty: "3",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/min-stack/",
    title: "Min stack",
    difficulty: "1",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/next-greater-element-i/",
    title: "Next greater element i",
    difficulty: "1",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/backspace-string-compare/",
    title: "Backspace string compare",
    difficulty: "1",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-queue-using-stacks/",
    title: "Implement queue using stacks",
    difficulty: "1",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-stack-using-queues/",
    title: "Implement stack using queues",
    difficulty: "1",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/",
    title: "Remove all adjacent duplicates in string ii",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/daily-temperatures/",
    title: "Daily temperatures",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flatten-nested-list-iterator/",
    title: "Flatten nested list iterator",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/online-stock-span/",
    title: "Online stock span",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/",
    title: "Minimum cost tree from leaf values",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sum-of-subarray-minimums/",
    title: "Sum of subarray minimums",
    difficulty: "2",
  },
  {
    topic: ["Stack"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    title: "Evaluate reverse polish notation",
    difficulty: "2",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lru-cache/",
    title: "Lru cache",
    difficulty: "3",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
    title: "Find median from data stream",
    difficulty: "2",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-underground-system/",
    title: "Design underground system",
    difficulty: "3",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lfu-cache/",
    title: "Lfu cache",
    difficulty: "2",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/tweet-counts-per-frequency/",
    title: "Tweet counts per frequency",
    difficulty: "2",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/all-oone-data-structure/",
    title: "All oone data structure",
    difficulty: "3",
  },
  {
    topic: ["Design"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-browser-history/",
    title: "Design browser history",
    difficulty: "3",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/employee-importance/",
    title: "Employee importance",
    difficulty: "1",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-town-judge/",
    title: "Find the town judge",
    difficulty: "1",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/evaluate-division/",
    title: "Evaluate division",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/accounts-merge/",
    title: "Accounts merge",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/network-delay-time/",
    title: "Network delay time",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-eventual-safe-states/",
    title: "Find eventual safe states",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/keys-and-rooms/",
    title: "Keys and rooms",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/possible-bipartition/",
    title: "Possible bipartition",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/",
    title: "Most stones removed with same row or column",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/regions-cut-by-slashes/",
    title: "Regions cut by slashes",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/satisfiability-of-equality-equations/",
    title: "Satisfiability of equality equations",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/as-far-from-land-as-possible/",
    title: "As far from land as possible",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-closed-islands/",
    title: "Number of closed islands",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
    title: "Number of operations to make network connected",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/",
    title:
      "Find the city with the smallest number of neighbors at a threshold distance",
    difficulty: "2",
  },
  {
    topic: ["Graph"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/time-needed-to-inform-all-employees/",
    title: "Time needed to inform all employees",
    difficulty: "2",
  },
  {
    topic: ["Bit Manipulation"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sum-of-two-integers/",
    title: "Sum of two integers",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    title: "Delete node in a linked list",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/middle-of-the-linked-list/",
    title: "Middle of the linked list",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/",
    title: "Convert binary number in a linked list to integer",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-hashset/",
    title: "Design hashset",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/",
    title: "Remove duplicates from sorted list",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/add-two-numbers/",
    title: "Add two numbers",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-linked-list/",
    title: "Reverse linked list",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    title: "Merge two sorted lists",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/copy-list-with-random-pointer/",
    title: "Copy list with random pointer",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/linked-list-cycle/",
    title: "Linked list cycle",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    title: "Intersection of two linked lists",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindrome-linked-list/",
    title: "Palindrome linked list",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-linked-list-elements/",
    title: "Remove linked list elements",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/design-hashmap/",
    title: "Design hashmap",
    difficulty: "1",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/add-two-numbers-ii/",
    title: "Add two numbers ii",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-linked-list-ii/",
    title: "Reverse linked list ii",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reorder-list/",
    title: "Reorder list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    title: "Remove nth node from end of list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
    title: "Flatten a multilevel doubly linked list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/partition-list/",
    title: "Partition list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/",
    title: "Remove duplicates from sorted list ii",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/odd-even-linked-list/",
    title: "Odd even linked list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sort-list/",
    title: "Sort list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/swap-nodes-in-pairs/",
    title: "Swap nodes in pairs",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotate-list/",
    title: "Rotate list",
    difficulty: "2",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    title: "Merge k sorted lists",
    difficulty: "3",
  },
  {
    topic: ["Linked List"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    title: "Reverse nodes in k group",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/k-closest-points-to-origin/",
    title: "K closest points to origin",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    title: "Kth largest element in an array",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reorganize-string/",
    title: "Reorganize string",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/furthest-building-you-can-reach/",
    title: "Furthest building you can reach",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
    title: "Kth smallest element in a sorted matrix",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    title: "Cheapest flights within k stops",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-most-competitive-subsequence/",
    title: "Find the most competitive subsequence",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/ugly-number-ii/",
    title: "Ugly number ii",
    difficulty: "2",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    title: "Merge k sorted lists",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sliding-window-maximum/",
    title: "Sliding window maximum",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/the-skyline-problem/",
    title: "The skyline problem",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/trapping-rain-water-ii/",
    title: "Trapping rain water ii",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
    title: "Minimum number of refueling stops",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/swim-in-rising-water/",
    title: "Swim in rising water",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/shortest-path-to-get-all-keys/",
    title: "Shortest path to get all keys",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/",
    title: "Minimum cost to hire k workers",
    difficulty: "3",
  },
  {
    topic: ["Heap"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/k-th-smallest-prime-fraction/",
    title: "K th smallest prime fraction",
    difficulty: "3",
  },
  {
    topic: ["Sliding Window"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/",
    title: "Longest substring with at least k repeating characters",
    difficulty: "2",
  },
  {
    topic: ["Sliding Window"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-consecutive-ones-iii/",
    title: "Max consecutive ones iii",
    difficulty: "2",
  },
  {
    topic: ["Sliding Window"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/grumpy-bookstore-owner/",
    title: "Grumpy bookstore owner",
    difficulty: "3",
  },
  {
    topic: ["Sliding Window"],
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sliding-window-median/",
    title: "Sliding window median",
    difficulty: "3",
  },
  {
    topic: ["Segment Tree"],
    status: false,
    note: "",
    url: "https://leetcode.com/articles/a-recursive-approach-to-segment-trees-range-sum-queries-lazy-propagation/",
    title:
      "A recursive approach to segment trees range sum queries lazy propagation",
    difficulty: "3",
  },
];
module.exports = sheet;
