sheet = {};
sheet.loveBabbarsheet = [
  {
    topic: "Array",
    title: "Reverse the array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-a-string/1",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Find the maximum and minimum element in an array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: 'Find the "Kth" max and min element of an array ',
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title:
      "Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Move all the negative elements to one side of the array ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Find the Union and Intersection of the two sorted arrays.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Write a program to cyclically rotate an array by one.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "find Largest sum contiguous Subarray [V. IMP]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Minimise the maximum difference between heights [V.IMP]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Minimum no. of Jumps to reach end of an array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "find duplicate in an array of N+1 Integers",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Merge 2 sorted arrays without using Extra space.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Kadane's Algo [V.V.V.V.V IMP]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    difficulty: "3",
  },
  {
    topic: "Array",
    title: "Merge Intervals",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-intervals/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Next Permutation",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/next-permutation/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Count Inversion",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Best time to buy and Sell stock",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "find all pairs on integer array whose sum is equal to given number",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "find common elements In 3 sorted arrays",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
    difficulty: "2",
  },
  {
    topic: "Array",
    title:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Find if there is any subarray with sum equal to 0",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Find factorial of a large number",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "find maximum product subarray ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Find longest coinsecutive subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Maximum profit by buying and selling a share atmost twice",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
    difficulty: "3",
  },
  {
    topic: "Array",
    title: "Find whether an array is a subset of another array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Find the triplet that sum to a given value",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Trapping Rain water problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Chocolate Distribution problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Smallest Subarray with sum greater than a given value",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/smallest-subarray-with-sum-greater-than-x/0",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Three way partitioning of an array around a given value",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Minimum swaps required bring elements less equal K together",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-swaps-required-to-bring-all-elements-less-than-or-equal-to-k-together/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Minimum no. of operations required to make an array palindrome",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/palindromic-array/0",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Median of 2 sorted arrays of equal size",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-the-median0527/1",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Median of 2 sorted arrays of different size",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/",
    difficulty: "3",
  },
  {
    topic: "Matrix",
    title: "Spiral traversal on a Matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Search an element in a matriix",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-a-2d-matrix/",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Find median in a row wise sorted matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Find row with maximum no. of 1's",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Print elements in sorted order using row-column wise sorted matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sorted-matrix/0",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Maximum size rectangle",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Find a specific pair in matrix",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/",
    difficulty: "3",
  },
  {
    topic: "Matrix",
    title: "Rotate matrix by 90 degrees",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/",
    difficulty: "2",
  },
  {
    topic: "Matrix",
    title: "Kth smallest element in a row-cpumn wise sorted matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kth-element-in-matrix/1",
    difficulty: "1",
  },
  {
    topic: "Matrix",
    title: "Common elements in all rows of a given matrix",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Reverse a String",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-string/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Check whether a String is Palindrome or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/palindrome-string0817/1",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Find Duplicate characters in a string",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Write a Code to check whether one string is a rotation of another",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Count and Say problem",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-and-say/",
    difficulty: "2",
  },
  {
    topic: "String",
    title:
      "Write a program to find the longest Palindrome in a string Longest palindromic Substring]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Find Longest Recurring Subsequence in String",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Print all Subsequences of a string.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/print-subsequences-string/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Print all the permutations of the given string",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Split the Binary string into two substring with equal 0’s and 1’s",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/split-the-binary-string-into-substrings-with-equal-number-of-0s-and-1s/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Word Wrap Problem [VERY IMP].",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/word-wrap/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "EDIT Distance [Very Imp]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Find next greater number with same set of digits. [Very Very IMP]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/next-permutation/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Balanced Parenthesis problem.[Imp]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Word break Problem[ Very Imp]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/word-break/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Rabin Karp Algo",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "KMP Algo",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1",
    difficulty: "2",
  },
  {
    topic: "String",
    title:
      "Convert a Sentence into its equivalent mobile numeric keypad sequence.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/convert-sentence-equivalent-mobile-numeric-keypad-sequence/",
    difficulty: "1",
  },
  {
    topic: "String",
    title:
      "Minimum number of bracket reversals needed to make an expression balanced.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-the-reversals/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Count All Palindromic Subsequence in a given String.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Count of number of given string in 2D character array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-count-number-given-string-present-2d-character-array/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Search a Word in a 2D Grid of characters.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-the-string-in-grid/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Boyer Moore Algorithm for Pattern Searching.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/boyer-moore-algorithm-for-pattern-searching/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "Converting Roman Numerals to Decimal",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/roman-number-to-integer/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Longest Common Prefix",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-common-prefix/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Number of flips to make binary string alternate",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/min-number-of-flips/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Find the first repeated word in string.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/second-most-repeated-string-in-a-sequence/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Minimum number of swaps for bracket balancing.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-swaps-for-bracket-balancing/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Find the longest common subsequence between two strings.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title:
      "Program to generate all possible valid IP addresses from given  string.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/program-generate-possible-valid-ip-addresses-given-string/",
    difficulty: "3",
  },
  {
    topic: "String",
    title:
      "Write a program to find the smallest window that contains all characters of string itself.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/smallest-distant-window/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title:
      "Rearrange characters in a string such that no two adjacent are same",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Minimum characters to be added at front to make string palindrome",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "Given a sequence of words, print all anagrams together",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title:
      "Find the smallest window in a string containing all characters of another string",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Recursively remove all adjacent duplicates",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/consecutive-elements/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "String matching where one string contains wildcard characters",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/wildcard-string-matching/0",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Function to find Number of customers who could not get a computer",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/function-to-find-number-of-customers-who-could-not-get-a-computer/",
    difficulty: "2",
  },
  {
    topic: "String",
    title:
      "Transform One String to Another using Minimum Number of Given Operation",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/transform-one-string-to-another-using-minimum-number-of-given-operation/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "Check if two given strings are isomorphic to each other",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/isomorphic-strings/0",
    difficulty: "2",
  },
  {
    topic: "String",
    title:
      "Recursively print all sentences that can be formed from list of word lists",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/recursively-print-all-sentences-that-can-be-formed-from-list-of-word-lists/",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "Find first and last positions of an element in a sorted array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/first-and-last-occurrences-of-x/0",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Find a Fixed Point (Value equal to index) in a given array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/value-equal-to-index-value1330/1",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Search in a rotated sorted array",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "square root of an integer",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-squares3649/1",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title:
      "Maximum and minimum of an array using minimum number of comparisons",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/middle-of-three2926/1",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Optimum location of point to minimize total distance",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/optimum-location-point-minimize-total-distance/",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "Find the repeating and the missing",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "find majority element",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/majority-element/0",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "Searching in an array where adjacent differ by at most k",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/searching-array-adjacent-differ-k/",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "find a pair with a given difference",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-pair-given-difference/0",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "find four elements that sum to a given value",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers/0",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "maximum sum such that no 2 elements are adjacent",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/stickler-theif/0",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Count triplet with sum smaller than a given value",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-triplets-with-sum-smaller-than-x5549/1",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "merge 2 sorted arrays",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "print all subarrays with 0 sum",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/zero-sum-subarrays/0",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "Product array Puzzle",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/product-array-puzzle/0",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Sort array according to count of set bits",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sort-by-set-bit-count/0",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "minimum no. of swaps required to sort the array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-swaps/1",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "K-th Element of Two Sorted Arrays",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array/0",
    difficulty: "2",
  },
  {
    topic: "Searching & Sorting",
    title: "Book Allocation Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "Job Scheduling Algo",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/weighted-job-scheduling-log-n-time/",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "Missing Number in AP",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/arithmetic-number/0",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Smallest number with atleastn trailing zeroes infactorial",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/smallest-factorial-number5929/1",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "Painters Partition Problem:",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0",
    difficulty: "1",
  },
  {
    topic: "Searching & Sorting",
    title: "Findthe inversion count",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
    difficulty: "3",
  },
  {
    topic: "Searching & Sorting",
    title: "Implement Merge-sort in-place",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/in-place-merge-sort/",
    difficulty: "3",
  },
  {
    topic: "LinkedList",
    title:
      "Write a Program to reverse the Linked List. (Both Iterative and recursive)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Reverse a Linked List in group of Given Size. [Very Imp]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Write a program to Detect loop in a linked list.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Write a program to Delete loop in a linked list.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Find the starting point of the loop. ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Remove Duplicates in a sorted Linked List.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Remove Duplicates in a Un-sorted Linked List.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title:
      "Write a Program to Move the last element to Front in a Linked List.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/move-last-element-to-front-of-a-given-linked-list/",
    difficulty: "Basic",
  },
  {
    topic: "LinkedList",
    title: "Add “1” to a number represented as a Linked List.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Add two numbers represented by linked lists.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Intersection of two Sorted Linked List.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Intersection Point of two Linked Lists.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Merge Sort For Linked lists.[Very Important]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Quicksort for Linked Lists.[Very Important]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/quick-sort-on-linked-list/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Find the middle Element of a linked list.",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/middle-of-the-linked-list/",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Check if a linked list is a circular linked list.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/circular-linked-list/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Split a Circular linked list into two halves.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/split-a-circular-linked-list-into-two-halves/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title:
      "Write a Program to check whether the Singly Linked list is a palindrome or not.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Deletion from a Circular Linked List.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/deletion-circular-linked-list/",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Reverse a Doubly Linked list.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-a-doubly-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Find pairs with a given sum in a DLL.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-pairs-given-sum-doubly-linked-list/",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title:
      "Count triplets in a sorted DLL whose sum is equal to given value “X”.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/count-triplets-sorted-doubly-linked-list-whose-sum-equal-given-value-x/",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Sort a “k”sorted Doubly Linked list.[Very IMP]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/sort-k-sorted-doubly-linked-list/",
    difficulty: "3",
  },
  {
    topic: "LinkedList",
    title: "Rotate DoublyLinked list by N nodes.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/rotate-doubly-linked-list-n-nodes/",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Rotate a Doubly Linked list in group of Given Size.[Very IMP]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/reverse-doubly-linked-list-groups-given-size/",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Flatten a Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Sort a LL of 0's, 1's and 2's",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/given-a-linked-list-of-0s-1s-and-2s-sort-it/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Clone a linked list with next and random pointer",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Merge K sorted Linked list",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Multiply 2 no. represented by LL",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/multiply-two-linked-lists/1",
    difficulty: "2",
  },
  {
    topic: "LinkedList",
    title: "Delete nodes which have a greater value on right side",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/delete-nodes-having-greater-value-on-right/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Segregate even and odd nodes in a Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list/0",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Program for n’th node from the end of a Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
    difficulty: "1",
  },
  {
    topic: "LinkedList",
    title: "Find the first non-repeating character from a stream of characters",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "level order traversal",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/level-order-traversal/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Reverse Level Order traversal",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-level-order-traversal/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Height of a tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Diameter of a tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Mirror of a tree",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/create-a-mirror-tree-from-the-given-binary-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Left View of a tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Right View of Tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Top View of a tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Bottom View of a tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Zig-Zag traversal of a binary tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Check if a tree is balanced or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Diagonal Traversal of a Binary tree",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/diagonal-traversal-of-binary-tree/",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Boundary traversal of a Binary tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Construct Binary Tree from String with Bracket Representation",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/construct-binary-tree-string-bracket-representation/",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Convert Binary tree into Doubly Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Convert Binary tree into Sum tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/transform-to-sum-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Construct Binary tree from Inorder and preorder traversal",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/construct-tree-1/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Find minimum swaps required to convert a Binary tree into BST",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-swap-required-convert-binary-tree-binary-search-tree/",
    difficulty: "3",
  },
  {
    topic: "Binary Trees",
    title: "Check if Binary tree is Sum tree or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sum-tree/1",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Check if all leaf nodes are at same level or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/leaf-at-same-level/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title:
      "Check if a Binary Tree contains duplicate subtrees of size 2 or more [ IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Check if 2 trees are mirror or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-mirror-in-n-ary-tree/0",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Sum of Nodes on the Longest path from root to leaf node ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sum-of-the-longest-bloodline-of-a-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Check if given graph is tree or not.  [ IMP ]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/check-given-graph-tree/",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Find Largest subtree sum in a tree",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-largest-subtree-sum-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Trees",
    title: "Maximum Sum of nodes in Binary tree such that no two are adjacent ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-sum-nodes-binary-tree-no-two-adjacent/",
    difficulty: "3",
  },
  {
    topic: "Binary Trees",
    title: 'Print all "K" Sum paths in a Binary tree',
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/print-k-sum-paths-binary-tree/",
    difficulty: "3",
  },
  {
    topic: "Binary Trees",
    title: "Find LCA in a Binary tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Find distance between 2 nodes in a Binary tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/min-distance-between-two-given-nodes-of-a-binary-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Kth Ancestor of node in a Binary tree",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/kth-ancestor-node-binary-tree-set-2/",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Find all Duplicate subtrees in a Binary tree [ IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/duplicate-subtrees/1",
    difficulty: "2",
  },
  {
    topic: "Binary Trees",
    title: "Tree Isomorphism Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-if-tree-is-isomorphic/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Fina a value in a BST",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/binary-search-tree-set-1-search-and-insertion/",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Deletion of a node in a BST",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/delete-node-in-a-bst/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Find min and max value in a BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Find inorder successor and inorder predecessor in a BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Check if a tree is a BST or not ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Populate Inorder successor of all nodes",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/populate-inorder-successor-for-all-nodes/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Find LCA  of 2 nodes in a BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Construct BST from preorder traversal",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/construct-bst-from-given-preorder-traversa/",
    difficulty: "3",
  },
  {
    topic: "Binary Search Trees",
    title: "Convert Binary tree into BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/binary-tree-to-bst/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Convert a normal BST into a Balanced BST",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/convert-normal-bst-balanced-bst/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Merge two BST [ V.V.V>IMP ]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/merge-two-balanced-binary-search-trees/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Find Kth largest element in a BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Find Kth smallest element in a BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-k-th-smallest-element-in-bst/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: 'Count pairs from 2 BST whose sum is equal to given value "X"',
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/brothers-from-different-root/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Trees",
    title: "Find the median of BST in O(n) time and O(1) space",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-median-bst-time-o1-space/",
    difficulty: "3",
  },
  {
    topic: "Binary Search Trees",
    title: "Count BST ndoes that lie in a given range",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-bst-nodes-that-lie-in-a-given-range/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Replace every element with the least greater element on its right",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/replace-every-element-with-the-least-greater-element-on-its-right/",
    difficulty: "3",
  },
  {
    topic: "Binary Search Trees",
    title: 'Given "n" appointments, find the conflicting appointments',
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/given-n-appointments-find-conflicting-appointments/",
    difficulty: "3",
  },
  {
    topic: "Binary Search Trees",
    title: "Check preorder is valid or not",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/preorder-to-postorder/0",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Check whether BST contains Dead end",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/check-whether-bst-contains-dead-end/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Largest BST in a Binary Tree [ V.V.V.V.V IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/largest-bst/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Trees",
    title: "Flatten BST to sorted list",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/flatten-bst-to-sorted-list-increasing-order/",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Activity Selection Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Job SequencingProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Huffman Coding",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/huffman-encoding/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Water Connection Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/water-connection-problem/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Fractional Knapsack Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/fractional-knapsack/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Greedy Algorithm to find Minimum number of Coins",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/coin-piles/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Maximum trains for which stoppage can be provided",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-trains-stoppage-can-provided/",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Minimum Platforms Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-platforms/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Buy Maximum Stocks if i stocks can be bought on i-th day",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/buy-maximum-stocks-stocks-can-bought-th-day/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Find the minimum and maximum amount to buy all N candies",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/shop-in-candy-store/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title:
      "Minimize Cash Flow among a given set of friends who have borrowed money from each other",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/",
    difficulty: "3",
  },
  {
    topic: "Greedy",
    title: "Minimum Cost to cut a board into squares",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-cost-cut-board-squares/",
    difficulty: "3",
  },
  {
    topic: "Greedy",
    title: "Check if it is possible to survive on Island",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/survival/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Find maximum meetings in one room",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Maximum product subset of an array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-product-subset-array/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Maximize array sum after K negations",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximize-sum-after-k-negations/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Maximize the sum of arr[i]*i",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximize-arrii-of-an-array/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Maximum sum of absolute difference of an array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-sum-absolute-difference-array/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Maximize sum of consecutive differences in a circular array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/swap-and-maximize/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Minimum sum of absolute difference of pairs of two arrays",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-sum-absolute-difference-pairs-two-arrays/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Program for Shortest Job First (or SJF) CPU Scheduling",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/program-for-shortest-job-first-or-sjf-cpu-scheduling-set-1-non-preemptive/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Program for Least Recently Used (LRU) Page Replacement algorithm",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/page-faults-in-lru/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Smallest subset with sum greater than all other elements",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/smallest-subset-sum-greater-elements/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Chocolate Distribution Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "K Centers Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/k-centers-problem-set-1-greedy-approximate-algorithm/",
    difficulty: "3",
  },
  {
    topic: "Greedy",
    title: "Minimum Cost of ropes",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Find smallest number with given number of digits and sum of digits",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/smallest-number5829/1",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title:
      "Rearrange characters in a string such that no two adjacent are same",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Find maximum sum possible equal sum of three stacks",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-maximum-sum-possible-equal-sum-three-stacks/",
    difficulty: "1",
  },
  {
    topic: "BackTracking",
    title: "Rat in a maze Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Printing all solutions in N-Queen Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/printing-solutions-n-queen-problem/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Word Break Problem using Backtracking",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/word-break-part-2/0",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Remove Invalid Parentheses",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-invalid-parentheses/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Sudoku Solver",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/solve-the-sudoku/0",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "m Coloring Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Print all palindromic partitions of a string",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Subset Sum Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "The Knight’s tour problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Tug of War",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/tug-of-war/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Find shortest safe route in a path with landmines",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-shortest-safe-route-in-a-path-with-landmines/",
    difficulty: "3",
  },
  {
    topic: "BackTracking",
    title: "Combinational Sum",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/combination-sum/0",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Find Maximum number possible by doing at-most K swaps",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/largest-number-in-k-swaps/0",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Print all permutations of a string ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Find if there is a path of more than k length from a source",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Longest Possible Route in a Matrix with Hurdles",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/longest-possible-route-in-a-matrix-with-hurdles/",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title:
      "Print all possible paths from top left to bottom right of a mXn matrix",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/print-all-possible-paths-from-top-left-to-bottom-right-of-a-mxn-matrix/",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Partition of a set intoK subsets with equal sum",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/partition-array-to-k-subsets/1",
    difficulty: "2",
  },
  {
    topic: "BackTracking",
    title: "Find the K-th Permutation Sequence of first N natural numbers",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-the-k-th-permutation-sequence-of-first-n-natural-numbers/",
    difficulty: "3",
  },
  {
    topic: "Stacks & Queues",
    title: " Implement Queue from Scratch",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Implement 2 stack in an array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "find the middle element of a stack",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/design-a-stack-with-find-middle-operation/",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: 'Implement "N" stacks in an Array',
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/efficiently-implement-k-stacks-single-array/",
    difficulty: "3",
  },
  {
    topic: "Stacks & Queues",
    title: "Check the expression has valid or Balanced parenthesis or not.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Reverse a String using Stack",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-a-string-using-stack/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title:
      "Design a Stack that supports getMin() in O(1) time and O(1) extra space.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/special-stack/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Find the next Greater element",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "The celebrity Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Arithmetic Expression evaluation",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/arithmetic-expression-evalution/",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Evaluation of Postfix expression",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/evaluation-of-postfix-expression/0",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Reverse a stack using recursion",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Sort a Stack using recursion",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Merge Overlapping Intervals",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/overlapping-intervals/0",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Largest rectangular Area in Histogram",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Length of the Longest Valid Substring",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/valid-substring0624/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Expression contains redundant bracket or not",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-not/",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Implement Stack using Queue",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Implement Stack using Deque",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/implement-stack-queue-using-deque/",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title:
      "Stack Permutations (Check if an array is stack permutation of other)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/stack-permutations-check-if-an-array-is-stack-permutation-of-other/",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Implement Queue using Stack  ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: 'Implement "n" queue in an array',
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/efficiently-implement-k-queues-single-array/",
    difficulty: "3",
  },
  {
    topic: "Stacks & Queues",
    title: "Implement a Circular queue",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/circular-queue-set-1-introduction-array-implementation/",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "LRU Cache Implementationa",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/lru-cache/1",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Reverse a Queue using recursion",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/queue-reversal/1",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Reverse the first “K” elements of a queue",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Interleave the first half of the queue with second half",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/interleave-first-half-queue-second-half/",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Find the first circular tour that visits all Petrol Pumps",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/circular-tour/1",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Minimum time required to rot all oranges",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rotten-oranges/0",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Distance of nearest cell having 1 in a binary matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/distance-of-nearest-cell-having-1/0",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "First negative integer in every window of size “k”",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/first-negative-integer-in-every-window-of-size-k/0",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Check if all levels of two trees are anagrams or not.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/check-if-all-levels-of-two-trees-are-anagrams-or-not/",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Sum of minimum and maximum elements of all subarrays of size “k”.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/sum-minimum-maximum-elements-subarrays-size-k/",
    difficulty: "3",
  },
  {
    topic: "Stacks & Queues",
    title:
      "Minimum sum of squares of character counts in a given string after removing “k” characters.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/game-with-string/0",
    difficulty: "1",
  },
  {
    topic: "Stacks & Queues",
    title: "Queue based approach or first non-repeating character in a stream.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
    difficulty: "2",
  },
  {
    topic: "Stacks & Queues",
    title: "Next Smaller Element",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/next-smaller-element/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Implement a Maxheap/MinHeap using arrays and recursion.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/building-heap-from-array/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Sort an Array using heap. (HeapSort)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/heap-sort/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Maximum of all subarrays of size k.",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/",
    difficulty: "3",
  },
  {
    topic: "Heap",
    title: "“k” largest element in an array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/k-largest-elements4206/1",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Kth smallest and largest element in an unsorted array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Merge “K” sorted arrays. [ IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Merge 2 Binary Max Heaps",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-two-binary-max-heap/0",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Kth largest sum continuous subarrays",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/k-th-largest-sum-contiguous-subarray/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Reorganize strings",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reorganize-string/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Merge “K” Sorted Linked Lists [V.IMP]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
    difficulty: "1",
  },
  {
    topic: "Heap",
    title: "Smallest range in “K” Lists",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-smallest-range-containing-elements-from-k-lists/1",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Median in a stream of Integers",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
    difficulty: "3",
  },
  {
    topic: "Heap",
    title: "Check if a Binary Tree is Heap",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/is-binary-tree-heap/1",
    difficulty: "3",
  },
  {
    topic: "Heap",
    title: "Connect “n” ropes with minimum cost",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0",
    difficulty: "1",
  },
  {
    topic: "Heap",
    title: "Convert BST to Min Heap",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/convert-bst-min-heap/",
    difficulty: "2",
  },
  {
    topic: "Heap",
    title: "Convert min heap to max heap",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/convert-min-heap-to-max-heap/",
    difficulty: "1",
  },
  {
    topic: "Heap",
    title:
      "Rearrange characters in a string such that no two adjacent are same.",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    difficulty: "1",
  },
  {
    topic: "Heap",
    title: "Minimum sum of two numbers formed from digits of an array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-sum4058/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Implement BFS algorithm ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Implement DFS Algo ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Detect Cycle in Directed Graph using BFS/DFS Algo ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Detect Cycle in UnDirected Graph using BFS/DFS Algo ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Search in a Maze",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Minimum Step by Knight",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/steps-by-knight/0",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "flood fill algo",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flood-fill/",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Clone a graph",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/clone-graph/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Making wired Connections",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "word Ladder ",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-ladder/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Dijkstra algo",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Implement Topological Sort ",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/topological-sort/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title:
      "Minimum time taken by each job to be completed given by a Directed Acyclic Graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-time-taken-by-each-job-to-be-completed-given-by-a-directed-acyclic-graph/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title:
      "Find whether it is possible to finish all tasks or not from given dependencies",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-whether-it-is-possible-to-finish-all-tasks-or-not-from-given-dependencies/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Find the no. of Islands",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title:
      "Given a sorted Dictionary of an Alien Language, find order of characters",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Implement Kruksal’sAlgorithm",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Implement Prim’s Algorithm",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Total no. of Spanning tree in a graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/total-number-spanning-trees-graph/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Implement Bellman Ford Algorithm",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/negative-weight-cycle/0",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Implement Floyd warshallAlgorithm",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall/0",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Travelling Salesman Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/travelling-salesman-problem-set-1/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Graph ColouringProblem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/graph-coloring-applications/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Snake and Ladders Problem",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/snakes-and-ladders/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Find bridge in a graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/bridge-in-a-graph/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Count Strongly connected Components(Kosaraju Algo)",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Check whether a graph is Bipartite or Not",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/bipartite-graph/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Detect Negative cycle in a graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/detect-negative-cycle-graph-bellman-ford/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Longest path in a Directed Acyclic Graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-longest-path-directed-acyclic-graph/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Cheapest Flights Within K Stops",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/description/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Water Jug problem using BFS",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/water-jug-problem-using-bfs/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Find if there is a path of more thank length from a source",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "M-ColouringProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Minimum edges to reverse o make path from source to destination",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-edges-reverse-make-path-source-destination/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Paths to travel each nodes using each edge(Seven Bridges)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/paths-travel-nodes-using-edgeseven-bridges-konigsberg/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Vertex Cover Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/vertex-cover-problem-set-1-introduction-approximate-algorithm-2/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Chinese Postman or Route Inspection",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/chinese-postman-route-inspection-set-1-introduction/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Number of Triangles in a Directed and Undirected Graph",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/number-of-triangles-in-directed-and-undirected-graphs/",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title:
      "Minimise the cashflow among a given set of friends who have borrowed money from each other",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/",
    difficulty: "3",
  },
  {
    topic: "Graph",
    title: "Two Clique Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/two-clique-problem-check-graph-can-divided-two-cliques/",
    difficulty: "3",
  },
  {
    topic: "Trie",
    title: "Construct a trie from scratch",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/trie-insert-and-search/",
    difficulty: "2",
  },
  {
    topic: "Trie",
    title: "Find shortest unique prefix for every word in a given list",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-all-shortest-unique-prefixes-to-represent-each-word-in-a-given-list/",
    difficulty: "3",
  },
  {
    topic: "Trie",
    title: "Word Break Problem | (Trie solution)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/word-break-problem-trie-solution/",
    difficulty: "2",
  },
  {
    topic: "Trie",
    title: "Given a sequence of words, print all anagrams together",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
    difficulty: "2",
  },
  {
    topic: "Trie",
    title: "Implement a Phone Directory",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/phone-directory/0",
    difficulty: "2",
  },
  {
    topic: "Trie",
    title: "Print unique rows in a given boolean matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/unique-rows-in-boolean-matrix/1",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Coin ChangeProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/coin-change2448/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Knapsack Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
    difficulty: "1",
  },
  {
    topic: "Dynamic Programming",
    title: "Binomial CoefficientProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/ncr1019/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Permutation CoefficientProblem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/permutation-coefficient/",
    difficulty: "1",
  },
  {
    topic: "Dynamic Programming",
    title: "Program for nth Catalan Number",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/program-nth-catalan-number/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Matrix Chain Multiplication ",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Edit Distance",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Subset Sum Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Friends Pairing Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/friends-pairing-problem5425/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Gold Mine Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/gold-mine-problem/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Assembly Line SchedulingProblem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/assembly-line-scheduling-dp-34/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Painting the Fenceproblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/painting-the-fence3727/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximize The Cut Segments",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/cutted-segments/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Common Subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Repeated Subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Increasing Subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Space Optimized Solution of LCS",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/space-optimized-solution-lcs/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "LCS (Longest Common Subsequence) of three strings",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/lcs-of-three-strings/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum Sum Increasing Subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Count all subsequences having product less than K",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/count-subsequences-product-less-k/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest subsequence such that difference between adjacent is one",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-subsequence-such-that-difference-between-adjacents-is-one4724/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum subsequence sum such that no three are consecutive",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-subsequence-sum-such-that-no-three-are-consecutive/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Egg Dropping Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum Length Chain of Pairs",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/max-length-chain/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum size square sub-matrix with all 1s",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/largest-square-formed-in-a-matrix/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum sum of pairs with specific difference",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/pairs-with-specific-difference/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Min Cost PathProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/path-in-matrix3805/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum difference of zeros and ones in binary string",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-difference-of-zeros-and-ones-in-binary-string4111/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Minimum number of jumps to reach end",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
    difficulty: "1",
  },
  {
    topic: "Dynamic Programming",
    title: "Minimum cost to fill given weight in a bag",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-cost-to-fill-given-weight-in-a-bag1956/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Minimum removals from array to make max –min <= K",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-removals-array-make-max-min-k/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Common Substring",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-common-substring/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Count number of ways to reacha given score in a game",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/reach-a-given-score/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Count Balanced Binary Trees of Height h",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bbt-counter/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "LargestSum Contiguous Subarray [V>V>V>V IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Smallest sum contiguous subarray",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/smallest-sum-contiguous-subarray/",
    difficulty: "1",
  },
  {
    topic: "Dynamic Programming",
    title: "Unbounded Knapsack (Repetition of items allowed)",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1",
    difficulty: "1",
  },
  {
    topic: "Dynamic Programming",
    title: "Word Break Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/word-break/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Largest Independent Set Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/largest-independent-set-problem-dp-26/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Partition problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Palindromic Subsequence",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Count All Palindromic Subsequence in a given String",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest Palindromic Substring",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Longest alternating subsequence",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/longest-alternating-subsequence/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Weighted Job Scheduling",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/weighted-job-scheduling/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Coin game winner where every player has three choices",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/coin-game-winner-every-player-three-choices/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title:
      "Count Derangements (Permutation such that no element appears in its original position) [ IMPORTANT ]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/count-derangements-permutation-such-that-no-element-appears-in-its-original-position/",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum profit by buying and selling a share at most twice [ IMP ]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Optimal Strategy for a Game",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/optimal-strategy-for-a-game/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Optimal Binary Search Tree",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/optimal-binary-search-tree-dp-24/",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Palindrome PartitioningProblem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Word Wrap Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/word-wrap/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Mobile Numeric Keypad Problem [ IMP ]",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Boolean Parenthesization Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/boolean-parenthesization/0",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Largest rectangular sub-matrix whose sum is 0",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/largest-rectangular-sub-matrix-whose-sum-0/",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title:
      "Largest area rectangular sub-matrix with equal number of 1’s and 0’s [ IMP ]",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/largest-area-rectangular-sub-matrix-equal-number-1s-0s/",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum sum rectangle in a 2D matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-sum-rectangle/0",
    difficulty: "2",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum profit by buying and selling a share at most k times",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/maximum-profit4657/1",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Find if a string is interleaved of two other strings",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/interleaved-strings/1",
    difficulty: "3",
  },
  {
    topic: "Dynamic Programming",
    title: "Maximum Length of Pair Chain",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-length-of-pair-chain/",
    difficulty: "2",
  },
  {
    topic: "Bit Manipulation",
    title: "Count set bits in an integer",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/set-bits0143/1",
    difficulty: "3",
  },
  {
    topic: "Bit Manipulation",
    title:
      "Find the two non-repeating elements in an array of repeating elements",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/finding-the-numbers0215/1",
    difficulty: "1",
  },
  {
    topic: "Bit Manipulation",
    title: "Count number of bits to be flipped to convert A to B",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bit-difference/0",
    difficulty: "1",
  },
  {
    topic: "Bit Manipulation",
    title: "Count total set bits in all numbers from 1 to n",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/count-total-set-bits/0",
    difficulty: "1",
  },
  {
    topic: "Bit Manipulation",
    title: "Program to find whether a no is power of two",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/power-of-2/0",
    difficulty: "1",
  },
  {
    topic: "Bit Manipulation",
    title: "Find position of the only set bit",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/find-position-of-set-bit3706/1",
    difficulty: "1",
  },
  {
    topic: "Bit Manipulation",
    title: "Copy set bits in a range",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/copy-set-bits-in-a-range/",
    difficulty: "2",
  },
  {
    topic: "Bit Manipulation",
    title:
      "Divide two integers without using multiplication, division and mod operator",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/",
    difficulty: "2",
  },
  {
    topic: "Bit Manipulation",
    title: "Calculate square of a number without using *, / and pow()",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/",
    difficulty: "2",
  },
  {
    topic: "Bit Manipulation",
    title: "Power Set",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/power-set4302/1",
    difficulty: "1",
  },
];
module.exports = sheet;
