sheet = {};
sheet.striverSheet = [
  {
    topic: "Array",
    title:
      "Sort an array of 0’s 1’s 2’s without using extra space or sorting algo",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sort-colors/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Repeat and Missing Number",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/find-a-repeating-and-a-missing-number/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Merge two sorted Arrays without extra space",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/efficiently-merging-two-sorted-arrays-with-o1-extra-space/",
    difficulty: "3",
  },
  {
    topic: "Array",
    title: "Maximum Subarray",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-subarray/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Merge Overlapping Subintervals",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-intervals/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Find the duplicate in an array of N+1 integers",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Set Matrix Zeroes",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/set-matrix-zeroes/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Pascal's Triangle",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/pascals-triangle/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Next Permutation",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/next-permutation/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Count Inversions in an array",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/counting-inversions/",
    difficulty: "3",
  },
  {
    topic: "Array",
    title: "Best Time to Buy and Sell Stock",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Rotate Image",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotate-image/",
    difficulty: "2",
  },

  {
    topic: "Maths",
    title: "Search a 2D Matrix",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-a-2d-matrix/",
    difficulty: "2",
  },
  {
    topic: "Maths",
    title: "Pow(x, n)",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/powx-n/",
    difficulty: "2",
  },
  {
    topic: "Maths",
    title: "Majority Element",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/majority-element/",
    difficulty: "1",
  },
  {
    topic: "Maths",
    title: "Majority Element II",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/majority-element-ii/",
    difficulty: "2",
  },
  {
    topic: "Maths",
    title: "Unique Paths",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/unique-paths/",
    difficulty: "2",
  },
  {
    topic: "Maths",
    title: "Reverse Pairs",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-pairs/",
    difficulty: "3",
  },

  {
    topic: "Hasing",
    title: "Two Sum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/two-sum/",
    difficulty: "1",
  },
  {
    topic: "Hasing",
    title: "4Sum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/4sum/",
    difficulty: "2",
  },
  {
    topic: "Hasing",
    title: "Longest Consecutive Sequence",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-consecutive-sequence/",
    difficulty: "2",
  },
  {
    topic: "Hasing",
    title: "Largest subarray with 0 sum",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1#",
    difficulty: "1",
  },
  {
    topic: "Hasing",
    title: "Count the number of subarrays having a given XOR",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/count-number-subarrays-given-xor/",
    difficulty: "3",
  },
  {
    topic: "Hasing",
    title: "Longest Substring Without Repeating Characters",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    difficulty: "2",
  },

  {
    topic: "Linked List",
    title: "Reverse Linked List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-linked-list/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Middle of the Linked List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/middle-of-the-linked-list/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Merge Two Sorted Lists",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Remove Nth Node From End of List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    difficulty: "2",
  },
  {
    topic: "Linked List",
    title: "Delete Node in a Linked List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Add Two Numbers",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/add-two-numbers/",
    difficulty: "2",
  },
  {
    topic: "Linked List",
    title: "Intersection of Two Linked Lists",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Linked List Cycle",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/linked-list-cycle/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Reverse Nodes in k-Group",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    difficulty: "3",
  },
  {
    topic: "Linked List",
    title: "Palindrome Linked List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindrome-linked-list/",
    difficulty: "1",
  },
  {
    topic: "Linked List",
    title: "Linked List Cycle II",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/linked-list-cycle-ii/",
    difficulty: "2",
  },
  {
    topic: "Linked List",
    title: "Flattening a Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1#",
    difficulty: "2",
  },
  {
    topic: "Linked List",
    title: "Rotate List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotate-list/",
    difficulty: "2",
  },
  {
    topic: "Two-Pointer",
    title: "Copy List with Random Pointer",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/copy-list-with-random-pointer/",
    difficulty: "2",
  },
  {
    topic: "Two-Pointer",
    title: "3Sum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/3sum/",
    difficulty: "2",
  },
  {
    topic: "Two-Pointer",
    title: "Trapping Rain Water",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/trapping-rain-water/",
    difficulty: "3",
  },
  {
    topic: "Two-Pointer",
    title: "Remove Duplicates from Sorted Array",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    difficulty: "1",
  },
  {
    topic: "Two-Pointer",
    title: "Max Consecutive Ones",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/max-consecutive-ones/",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "N meetings in one room",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1#",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Minimum Platforms",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1#",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Job Sequencing Problem",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1#",
    difficulty: "2",
  },
  {
    topic: "Greedy",
    title: "Fractional Knapsack",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1#",
    difficulty: "1",
  },
  {
    topic: "Greedy",
    title: "Greedy Algorithm to find Minimum number of Coins",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/greedy-algorithm-to-find-minimum-number-of-coins/",
    difficulty: "1",
  },
  {
    topic: "Recursion",
    title: "Subset Sums",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/subset-sums2234/1#",
    difficulty: "1",
  },
  {
    topic: "Recursion",
    title: "Subsets II",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subsets-ii/",
    difficulty: "2",
  },
  {
    topic: "Recursion",
    title: "Combination Sum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/combination-sum/",
    difficulty: "2",
  },
  {
    topic: "Recursion",
    title: "Combination Sum II",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/combination-sum-ii/",
    difficulty: "2",
  },
  {
    topic: "Recursion",
    title: "Palindrome Partitioning",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/palindrome-partitioning/",
    difficulty: "2",
  },
  {
    topic: "Recursion",
    title: "Permutation Sequence",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/permutation-sequence/",
    difficulty: "3",
  },
  {
    topic: "Backtracking",
    title: "Permutations",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/permutations/",
    difficulty: "2",
  },
  {
    topic: "Backtracking",
    title: "N-Queens",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/n-queens-ii/",
    difficulty: "3",
  },
  {
    topic: "Backtracking",
    title: "Sudoku Solver",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sudoku-solver/",
    difficulty: "3",
  },
  {
    topic: "Backtracking",
    title: "m Coloring Problem",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/",
    difficulty: "2",
  },
  {
    topic: "Backtracking",
    title: "Rat in a Maze",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1#",
    difficulty: "2",
  },
  {
    topic: "Backtracking",
    title: "Word Break",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/word-break/",
    difficulty: "2",
  },
  {
    topic: "Binary Search",
    title: "Calculating n-th real root using binary search",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/calculating-n-th-real-root-using-binary-search/",
    difficulty: "2",
  },
  {
    topic: "Binary Search",
    title: "Median in a row-wise sorted Matrix",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1#",
    difficulty: "2",
  },
  {
    topic: "Binary Search",
    title: "Single Element in a Sorted Array",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    difficulty: "2",
  },
  {
    topic: "Binary Search",
    title: "Search in Rotated Sorted Array",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    difficulty: "2",
  },
  {
    topic: "Binary Search",
    title: "Median of Two Sorted Arrays",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    difficulty: "3",
  },
  {
    topic: "Binary Search",
    title: "K-th Element of Two Sorted Arrays",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/",
    difficulty: "3",
  },
  {
    topic: "Bits",
    title: "Power of Two",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/power-of-two/",
    difficulty: "1",
  },
  {
    topic: "Bits",
    title: "Counting Bits",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/counting-bits/",
    difficulty: "1",
  },
  {
    topic: "Bits",
    title:
      "Divide two integers without using multiplication, division and mod operator",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/",
    difficulty: "2",
  },
  {
    topic: "Bits",
    title: "Subsets",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/subsets/",
    difficulty: "2",
  },
  {
    topic: "Bits",
    title: "Calculate square of a number without using *, / and pow()",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/",
    difficulty: "2",
  },

  {
    topic: ["Stack", "Queue"],
    title: "Implement stack using array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1#",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Implement Queue using array",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1#",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Implement Stack using Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implement-stack-using-linked-list/1",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Implement Queue using Linked List",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/implement-queue-using-linked-list/1",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "BFS of graph",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1#",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Implement Stack using Queues",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-stack-using-queues/",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Implement Queue using Stacks",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-queue-using-stacks/",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Valid Parentheses",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/valid-parentheses/",
    difficulty: "1",
  },
  {
    topic: ["Stack", "Queue"],
    title: "Next Greater Element",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/next-larger-element-1587115620/1#",
    difficulty: "2",
  },
  {
    topic: "Two-Pointer",
    title: "LRU Cache",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lru-cache/",
    difficulty: "2",
  },
  {
    topic: "Two-Pointer",
    title: "Largest Rectangle in Histogram",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    difficulty: "3",
  },
  {
    topic: "Two-Pointer",
    title: "Sliding Window Maximum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/sliding-window-maximum/",
    difficulty: "3",
  },
  {
    topic: "Two-Pointer",
    title: "Min Stack",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/min-stack/",
    difficulty: "1",
  },
  {
    topic: "Two-Pointer",
    title: "Rotting Oranges",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/rotting-oranges/",
    difficulty: "2",
  },

  {
    topic: "String",
    title: "Reverse Words in a String",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/reverse-words-in-a-string/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Longest Palindromic Substring",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Roman to Integer",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/roman-to-integer/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Integer to Roman",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/integer-to-roman/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Implement strStr",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/implement-strstr/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "String to Integer",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/string-to-integer-atoi/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Longest Common Prefix",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/longest-common-prefix/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Rabin-Karp Algorithm for Pattern Searching",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Z algorithm (Linear time pattern searching Algorithm)",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/z-algorithm-linear-time-pattern-searching-algorithm/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "KMP Algorithm for Pattern Searching",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "Minimum characters to be added at front to make string palindrome",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/",
    difficulty: "3",
  },
  {
    topic: "String",
    title: "Valid Anagram",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/valid-anagram/",
    difficulty: "1",
  },
  {
    topic: "String",
    title: "Count and Say",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/count-and-say/",
    difficulty: "2",
  },
  {
    topic: "String",
    title: "Compare Version Numbers",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/compare-version-numbers/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Inorder Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Preorder Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Postorder Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Right Side View",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Bottom View of Binary Tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1#",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Top View of Binary Tree",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Level Order Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Zigzag Level Order Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Maximum Depth of Binary Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Diameter of Binary Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/diameter-of-binary-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Balanced Binary Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/balanced-binary-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Lowest Common Ancestor of a Binary Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Same Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/same-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree Maximum Path Sum",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    difficulty: "3",
  },
  {
    topic: "Binary Tree",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
    difficulty: "2",
  },
  {
    topic: "Binary Tree",
    title: "Symmetric Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/symmetric-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Tree",
    title: "Flatten Binary Tree to Linked List",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Populating Next Right Pointers in Each Node",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Search in a Binary Search Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Convert Sorted Array to Binary Search Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Validate Binary Search Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Lowest Common Ancestor of a BST",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Predecessor and Successor",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1#",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Floor and Ceil from a BST",
    status: false,
    note: "",
    url: "https://www.geeksforgeeks.org/floor-and-ceil-from-a-bst/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Kth Smallest Element in a BST",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Kth largest element in BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Two Sum IV - Input is a BST",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
    difficulty: "1",
  },
  {
    topic: "Binary Search Tree",
    title: "Binary Search Tree Iterator",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/binary-search-tree-iterator/",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Largest BST",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/largest-bst/1",
    difficulty: "2",
  },
  {
    topic: "Binary Search Tree",
    title: "Serialize and Deserialize Binary Tree",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    difficulty: "3",
  },
  {
    topic: "Binary Tree",
    title: "Binary Tree to DLL",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1#",
    difficulty: "3",
  },
  {
    topic: "Maths",
    title: "Find Median from Data Stream",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
    difficulty: "3",
  },
  {
    topic: "Maths",
    title: "Kth Largest Element in a Stream",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    difficulty: "1",
  },
  {
    topic: "Array",
    title: "Kth Largest Element in an Array",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    difficulty: "2",
  },
  {
    topic: "Array",
    title: "Flood Fill",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/flood-fill/",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Clone Graph",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/clone-graph/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "DFS of Graph",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1#",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "BFS of graph",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
    difficulty: "1",
  },
  {
    topic: "Graph",
    title: "Detect cycle in an undirected graph",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1#",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Detect cycle in a directed graph",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1#",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Topological sort",
    status: false,
    note: "",
    url: "https://practice.geeksforgeeks.org/problems/topological-sort/1#",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Number of Islands",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/number-of-islands/",
    difficulty: "2",
  },
  {
    topic: "Graph",
    title: "Is Graph Bipartite?",
    status: false,
    note: "",
    url: "https://leetcode.com/problems/is-graph-bipartite/",
    difficulty: "2",
  },
];
module.exports = sheet;
